<?php
/**
* Copyright (C) 2020  Zigly
* @package   Zigly_Sales
*/

/** @var \Magento\Sales\Block\Order\Items $block */
?>
<?php $blockObj = $block->getLayout()->createBlock('Zigly\Sales\Block\Order\History');?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" summary="<?= $block->escapeHtml(__('Items Ordered')) ?>">
        <caption class="table-caption"><?= $block->escapeHtml(__('Items Ordered')) ?></caption>
        <thead>
            <?php if ($block->isPagerDisplayed()) : ?>
                <tr>
                    <td colspan="5" data-block="order-items-pager-top" class="order-pager-wrapper order-pager-wrapper-top">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif ?>
        </thead>
        <?php $items = $block->getItems(); ?>
        <?php $giftMessage = ''?>
        <?php foreach ($items as $item) :
            if ($item->getParentItem()) :
                continue;
            endif;
            ?>
            <tbody>
                <!-- <?php // $block->getItemHtml($item) ?> -->
                <tr class="order-product-head">
                    <td>
                        <?php $imageurl = $blockObj->getProductImage($item->getProductId()); ?>
                        <p class="product-image">
                            <img src="<?php echo $imageurl?>"/>
                        </p>
                    </td>
                    <td>
                        <p class="product-name">
                            <?= $block->escapeHtml($item->getName()) ?>
                        </p>
                        <?php $resultOptions = [];
                        $options = $item->getProductOptions();
                        if ($options) {
                            if (isset($options['options'])) {
                                $resultOptions = array_merge($resultOptions, $options['options']);
                            }
                            if (isset($options['additional_options'])) {
                                $resultOptions = array_merge($resultOptions, $options['additional_options']);
                            }
                            if (isset($options['attributes_info'])) {
                                $resultOptions = array_merge($resultOptions, $options['attributes_info']);
                            }
                        } ?>
                        <?php if($resultOptions):?>
                            <?php foreach($resultOptions as  $option):?>
                                <dl class="product-options">
                                    <dd><?php echo $option['value'] ?></dd>
                                </dl>
                            <?php endforeach ?>
                        <?php endif ?>
                        <dl>
                            <dd>
                                <span class="order-qty">
                                    <?= $block->escapeHtml(__('Qty: ')) ?><?= round($item->getQtyOrdered()) ?>
                                </span>
                                <span class="order-price">
                                    <?= $block->escapeHtml(__('Price: ')) ?><?= $blockObj->currency(number_format((float)$item->getBaseRowTotal(), 0, '', '')) ?>
                                </span>
                                <!-- <div class="item-delivered-on">
                                    <label>Delivered on 1 March, 2021</label>
                                </div> -->
                            </dd>
                        </dl>
                    </td>
                    <td>
                        <dl class="product-actions">
                            <?php $status = ['complete']; ?>
                            <?php if (in_array($blockObj->getOrderStatus($item->getOrderId()), $status)) { ?>
                                <?php $review = $blockObj->reviewenable($item->getProductId()); ?>
                                <?php $url = $blockObj->getProductUrl($item->getProductId()); ?>
                                <?php if ($review) { ?>
                                    <?php if (!empty($url)) : ?>
                                        <dd>
                                            <?php $urlForm = $url . '#review-form'; ?>
                                            <a href="<?= $urlForm ?>" class="write-review">
                                                <span><?= $block->escapeHtml(__('Write Review')) ?></span>
                                            </a>
                                        </dd>
                                    <?php endif; ?>
                                <?php } ?>
                            <?php } ?>
                        </dl>
                    </td>
                </tr>
            </tbody>
        <?php endforeach; ?>
        <tfoot>
            <?php if ($block->isPagerDisplayed()) : ?>
                <tr>
                    <td colspan="5" data-block="order-items-pager-bottom" class="order-pager-wrapper order-pager-wrapper-bottom">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif ?>
            <!-- <?php // $block->getChildHtml('order_totals') ?> -->
        </tfoot>
    </table>
</div>
<?php if ($giftMessage) : ?>
<script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>