<?php
/**
* Copyright (C) 2020  Zigly
* @package   Zigly_Sales
*/
?>
<div class="my-orders-menu">
     <ul class="orders-side-menu">
          <li class="<?php if($this->SetActive() == "sales_orders_booking" || $this->SetActive() == "sales_orders_viewbooking") { echo "active"; } ?>">
               <div class="order-booking">
                    <a href="<?php echo $this->getUrl('sales/orders/booking');?>" class="action">
                       <span><?= $block->escapeHtml(__('Bookings')) ?></span>
                    </a>
               </div>
               <span><?= $block->escapeHtml(__('View Upcoming And Past Bookings')) ?></span>
          </li>
          <!-- <li>
               <div class="order-package">
                    <a href="#" class="action">
                       <span><?php // $block->escapeHtml(__('Packages')) ?></span>
                    </a>
               </div>
               <span><?php // $block->escapeHtml(__('Manage your service package')) ?></span>
          </li> -->
          <li class="<?php if($this->SetActive() == "sales_orders_history" || $this->SetActive() == "sales_orders_view") { echo "active"; } ?>">
               <div class="order-purchase">
                    <a href="<?php echo $this->getUrl('sales/orders/history');?>" class="action">
                       <span><?= $block->escapeHtml(__('Product Purchases')) ?></span>
                    </a>
               </div>
               <span><?= $block->escapeHtml(__('Track your product purchases')) ?></span>
          </li>
          <!-- <li>
               <div class="order-subscription">
                    <a href="#" class="action">
                       <span><?php // $block->escapeHtml(__('Subscription')) ?></span>
                    </a>
               </div>
               <span><?php // $block->escapeHtml(__('Manage your subsription package')) ?></span>
          </li> -->
     </ul>
</div>