<?php
/**
 * @var \Zigly\Sales\Block\Order\Booking $block
 */ 
$booking = $this->getBookingById();
$professional = $this->getProfessionalById($booking->getGroomerId());
$image = '';
$description = '';
if ($booking->getPlanid()) {
    $plan = $this->getPlans($booking->getPlanid());
    $image = $plan->getPlanImage();
    $description = $plan->getDescription();
}
$experience = $professional->getData('year_of_experience');
$experience = ($experience == 0 || $experience == NULL)? 'Experience: 0 Years': "Experience: $experience Years";
$planImage = $this->getPlanImage($image);
$reviewStatus = $block->getreviewStatus(); ?>
<div class="booking-back">
    <a href="<?php echo $this->getUrl('sales/orders/booking');?>" class="action sales-order-booking-back">
        <span><?= $block->escapeHtml(__('Back')) ?></span>
    </a>
</div>
<div class="sales-order-view-booking">
    <div class="booking-plan-detail">
        <div class="plan-image">
            <img class="imageThumb" src="<?php echo $planImage ?>">
        </div>
        <div class="plan-name"><?= /* @noEscape */ $booking->getPlanName() ?></div>
        <?php if (!empty($description)) : ?>
            <div class="plan-description"><?= /* @noEscape */ $description ?></div>
        <?php endif; ?>
        <div class="plan-price"><?= /* @noEscape */ $this->currency(number_format((float)$booking->getSubtotal(), 2, '.', '')) ?></div>
        <div class="plan-view">
            <a href="javascript:;" class="view-plan-details"><?= __('View Details') ?></a>
            <span class="duration">
                <?= $block->escapeHtml(__('60 Mins')) ?>
            </span>
            <?php $activities = json_decode($booking->getPlanActivites()); ?>
            <?php if (!empty($activities)) : ?>
                <div class="detail-options" style="display: none;">
                    <ul class="lists">
                        <?php foreach($activities as $value) : ?>
                            <li class="list-option"><?= $value ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif;?>
        </div>
        <div class="booking-status">
            <label><?= $block->escapeHtml(__('Status: ')) ?></label>
            <label><?= $block->escapeHtml($block->getStatus($booking->getBookingStatus())) ?></label>
        </div>
        <div class="booking-date-time">
            <span><?= /* @noEscape */ $this->getDate($booking->getScheduledDate()) ?></span>
            <span><?= /* @noEscape */ $booking->getScheduledTime() ?></span>
        </div>
        <div class="booking-address">
            <span class="address">
                <?= $block->escapeHtml($booking->getStreet().', ') ?>
                <?= $block->escapeHtml($booking->getRegion().', ') ?>
                <?= $block->escapeHtml($booking->getCity().', ') ?> <?= $block->escapeHtml($booking->getPostcode()) ?>
            </span>
        </div>
    </div>
    <div class="booking-groomer-detail">
        <?php if ($professional->getGroomerId()){ ?>
            <div class="groomer-info">
                <div class="user-verified">
                    <div>
                        <img class="imageThumb" src="<?php echo $this->getProfessionalimage($professional->getProfileImage()); ?>">
                    </div>
                    <span><?= $block->escapeHtml(__('Zigly Verified')) ?></span>
                </div>
                <div class="professional-name-rating">
                    <label><?= $professional->getName() ?></label>
                    <?php if (!empty($professional->getOverallRating())) {?>
                        <label class="overall-rating"><?= $professional->getOverallRating() ?></label>
                    <?php } ?>
                    <!-- <div>
                        <a href="#" class="call"></a><?= $block->escapeHtml(__('|')) ?>
                        <a href="#" class="msg"></a>
                    </div> -->
                </div>
                <?php if ($booking->getCenter() == "At Home" || $booking->getCenter() == "In-Clinic Appointments") : ?>
                    <div class="professional-exp-certificate">
                        <p><?= $block->escapeHtml(__($experience)) ?></p>
                        <?php if(!empty($professional->getData('certification'))){ ?>
                            <div>
                                <p><?= $block->escapeHtml(__('Certification(s): ')) ?></p>
                                <p><?= $block->escapeHtml(__($professional->getData('certification'))) ?></p>
                            </div>
                        <?php } ?>
                    </div>
                <?php endif; ?>
                <?php $date = new \DateTime($booking->getScheduledDate().'+10 days'); ?>
                <?php $date->setTimezone(new \DateTimeZone('Asia/Kolkata'));?>
                <?php $currentTimeStamp = $date->getTimestamp() + $date->getOffset(); ?>
                <?php $today = new \DateTime('now', new \DateTimeZone('Asia/Kolkata')); ?>
                <?php $todayTimeStamp = $today->getTimestamp() + $today->getOffset(); ?>
            </div>
             <?php if (!empty($reviewStatus) && $reviewStatus[0]['review'] == 0 && !empty($reviewStatus[0]['groomer_id']) && $reviewStatus[0]['booking_status'] == 'Completed' && ($todayTimeStamp < $currentTimeStamp)) {?>
                    <div class="groomer-review-btn">
                        <button id="groomer-review-link" class="action submit primary">Write A Review</button>
                    </div>
            <?php } ?>
            <div class="product data items" data-mage-init='{"mage/tabs": {"openedState": "active", "animate": {"duration": 100}, "active": 0, "disabled": [2], "disabledState": "disabled"}}'>
                <div class="tabs-title">
                    <?php if (!empty($professional->getDescription())) { ?>
                        <div class="item title" data-role="collapsible">
                            <a class="switch" data-toggle="trigger" href="javascript:void(0);">ABOUT</a>
                        </div>
                    <?php } ?>
                    <div class="item title" data-role="collapsible">
                        <a class="switch" data-toggle="trigger" href="javascript:void(0);">REVIEWS</a>
                    </div>
                </div>
                <?php if (!empty($professional->getDescription())) { ?>
                    <div id="tab-about" class="item content" data-role="content">
                        <?= $professional->getDescription() ?>
                    </div>
                <?php } ?>
              <!--   <div class="item title" data-role="collapsible">
                    <a class="switch" data-toggle="trigger" href="javascript:void(0);">REVIEWS</a>
                </div> -->
                <div id="tab-reviews" class="item content" data-role="content">
                    <?php $groomerReview = $this->getProfessionalReviewById($booking->getGroomerId());
                    if (count($groomerReview)) {
                        foreach ($groomerReview as $key => $value) { ?>
                            <p class="customer-name"><?= $value['customer_name'] ?></p>
                            <div class="review-block">
                                <div class="rating-review">
                                    <div class="nested product-review-table" id="product-review-table">
                                       <div class="choice review-field-rating">
                                          <div class="rating-stars-block">
                                            <input type="radio" <?php if ($value['star_rating'] == 5) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                            <label class="rating-star rating-5" for="Feedback_5" title="<?= $value['star_rating'] ?> stars" id="Feedback_5_label">
                                            </label>
                                            <input type="radio" <?php if ($value['star_rating'] == 4) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                            <label class="rating-star rating-4" for="Feedback_4" title="<?= $value['star_rating'] ?> stars" id="Feedback_4_label">
                                            </label>
                                            <input type="radio" <?php if ($value['star_rating'] == 3) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                            <label class="rating-star rating-3" for="Feedback_3" title="<?= $value['star_rating'] ?> stars" id="Feedback_3_label">
                                            </label>
                                            <input type="radio" <?php if ($value['star_rating'] == 2) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                            <label class="rating-star rating-2" for="Feedback_2" title="<?= $value['star_rating'] ?> stars" id="Feedback_2_label">
                                            </label>
                                            <input type="radio" <?php if ($value['star_rating'] == 1) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                            <label class="rating-star rating-1" for="Feedback_1" title="<?= $value['star_rating'] ?> star" id="Feedback_1_label">
                                            </label>
                                          </div>
                                       </div>
                                    </div>
                                    <p class="review-create_at"><?= 'Reviewed '.$this->reviewedAtFormat($value['created_at']) ?></p>
                                </div>
                                <div><?= $value['description'] ?></div>
                            </div>
                        <?php }
                    } else { ?>
                        <p>No review's found.</p>
                    <?php } ?>
                    <?php $date = new \DateTime($booking->getScheduledDate().'+10 days'); ?>
                    <?php $date->setTimezone(new \DateTimeZone('Asia/Kolkata'));?>
                    <?php $currentTimeStamp = $date->getTimestamp() + $date->getOffset(); ?>
                    <?php $today = new \DateTime('now', new \DateTimeZone('Asia/Kolkata')); ?>
                    <?php $todayTimeStamp = $today->getTimestamp() + $today->getOffset(); ?>
                    <?php if (!empty($reviewStatus) && $reviewStatus[0]['review'] == 0 && !empty($reviewStatus[0]['groomer_id']) && $reviewStatus[0]['booking_status'] == 'Completed' && ($todayTimeStamp < $currentTimeStamp)) : ?>
                        <!-- <div data-mage-init='{"reviewpopup": {}}'>
                            <button id="groomer-review-link" class="action submit primary">Write A Review</button>
                        </div> -->
                        <div id="popup-modal-review-tag" style="display:none">
                            <form action="<?= $block->getUrl('groomerreview/groomerreview/Save') ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'" novalidate="novalidate" data-mage-init='{"validation": {"rules": {"star_rating": {"required":true}}}}' data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" >
                                <?= $block->getBlockHtml('formkey') ?>
                                <?= $block->getChildHtml('form_fields_before') ?>
                                <fieldset class="fieldset review-fieldset" data-hasrequired="* Required Fields">
                                    <fieldset class="field required review-field-star_rating">
                                        <div class="nested product-review-table" id="product-review-table">
                                           <div class="choice review-field-rating">
                                              <div class="rating-stars-block">
                                                <input type="radio" name="star_rating" id="Feedback_5" value="5" class="radio reviewstar"  aria-labelledby="Feedback_rating_label Feedback_5_label">
                                                <label class="rating-star rating-5" for="Feedback_5" title="5 stars" id="Feedback_5_label">
                                                </label>
                                                <input type="radio" name="star_rating" id="Feedback_4" value="4" class="radio reviewstar"  aria-labelledby="Feedback_rating_label Feedback_4_label">
                                                <label class="rating-star rating-4" for="Feedback_4" title="4 stars" id="Feedback_4_label">
                                                </label>
                                                <input type="radio" name="star_rating" id="Feedback_3" value="3" class="radio reviewstar"  aria-labelledby="Feedback_rating_label Feedback_3_label">
                                                <label class="rating-star rating-3" for="Feedback_3" title="3 stars" id="Feedback_3_label">
                                                </label>
                                                <input type="radio" name="star_rating" id="Feedback_2" value="2" class="radio reviewstar"  aria-labelledby="Feedback_rating_label Feedback_2_label">
                                                <label class="rating-star rating-2" for="Feedback_2" title="2 stars" id="Feedback_2_label">
                                                </label>
                                                <input type="radio" name="star_rating" id="Feedback_1" value="1" class="radio reviewstar" aria-labelledby="Feedback_rating_label Feedback_1_label">
                                                <label class="rating-star rating-1" for="Feedback_1" title="1 star" id="Feedback_1_label">
                                                </label>
                                              </div>
                                           </div>
                                        </div>
                                    </fieldset>
                                    <fieldset class="field required review-field-rating-description">
                                        <div class="field review-field-Tags"></div>
                                        <div class="field review-field-description">
                                            <div class="admin__field-control">
                                                <textarea name="description" data-validate='{"minlength":2,"maxlength":200}' id="description" title="Write Feedback (optional)" class="input-text" placeholder="Write Feedback (optional)" rows="4" cols="15"></textarea>
                                            </div>
                                        </div>
                                         <div class="field review-field-groomerid">
                                            <div class="control">
                                               <input name="groomer_id" type="hidden" title="Groomer Id" value="<?= $professional->getGroomerId() ?>">
                                            </div>
                                         </div>
                                         <div class="field review-field-serviceid">
                                            <div class="control">
                                               <input name="service_id" type="hidden" title="Service Id" value="<?= $block->getBookingId() ?>">
                                            </div>
                                         </div>
                                        <div class="review-form-actions">
                                             <button type="submit" class="action submit primary" title="Send Review" aria-label="Send Review"><?= $block->escapeHtmlAttr(__('SUBMIT')) ?></button>
                                        </div>
                                    </fieldset>
                                </fieldset>
                               </form>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            <?php } ?>
        <div class="booking-price-status">
            <label class="price"><?= $block->escapeHtml(__('Amount')) ?><?= /* @noEscape */ $this->currency(number_format((float)$booking->getGrandTotal(), 2, '.', '')) ?></label>
            <?php if ($booking->getWalletMoney()) : ?>
                <label class="wallet-used"><?= $block->escapeHtml(__('Wallet used: ')).''.$this->currency((float)$booking->getWalletMoney()) ?></label>
            <?php endif; ?>
            <?php if (!empty($booking->getCouponCode())) : ?>
                <label class="wallet-used"><?= $block->escapeHtml(__('Discount: ')).''.$this->currency((float)$booking->getCouponAmount()) ?></label>
            <?php endif; ?>
            <label><?= $block->escapeHtml(__('Payment Status: ').$booking->getPaymentStatus()) ?></label>
        </div>
        <div class="booking-action">
            <?php $now = new \DateTime('now', new \DateTimeZone('Asia/Kolkata')); ?>
            <?php $currentTimeStamp = $now->getTimestamp() + $now->getOffset(); ?>
            <?php if ($booking->getGroomerId() && ($currentTimeStamp < $booking->getScheduledTimestamp())) { ?>
                <?php $scheduledStatus = ['Scheduled']; ?>
                <?php if (in_array($booking->getBookingStatus(), $scheduledStatus)) { ?>
                    <a href="<?=  $block->getUrl('sales/booking/reschedule' , ['id' => $booking->getEntityId()]) ?>" class="action booking-reschedule">
                        <span><?= $block->escapeHtml(__('Reschedule')) ?></span>
                    </a>
                <?php } ?>
                <?php $status = ['Scheduled', 'Inprogress', 'Rescheduled by Admin', 'Rescheduled by Customer']; ?>
                <?php $now->add(new \DateInterval('PT30M')); ?>
                <?php $currentTimeStamp = $now->getTimestamp() + $now->getOffset(); ?>
                <?php if (in_array($booking->getBookingStatus(), $status) && ($currentTimeStamp < $booking->getScheduledTimestamp())) { ?>
                    <a href="#" key="<?php /* @noEscape */ echo $booking->getEntityId()?>" class="action booking-cancel">
                        <span><?= $block->escapeHtml(__('Cancel')) ?></span>
                    </a>
                <?php } ?>
            <?php } ?>
            <span class="help-tooltip">
                <a href="javascript:;" class="tooltip-toggle booking-help"><?= $block->escapeHtml(__('Help')) ?></a>
                <span class="tooltip-content"><?= __('For any queries or concern you can write to us at support@zigly.com or call us on +918069601281') ?></span>
            </span>
            <?php $invoiceStatus = ['pending', 'canceled']; ?>
            <?php if (!in_array($booking->getBookingStatus(), $invoiceStatus)) { ?>
                <a href="javascript:;" target="_blank" class="action view service-generate-invoice" key="<?=$booking->getEntityId()?>">
                    <span><?= $block->escapeHtml(__('Download Invoice')) ?></span>
                </a>
            <?php } ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_Sales/js/cancel": {
                "bookingUrl" : "<?php echo $this->getUrl().'sales/orders/cancelbooking'?>",
                "policy" : "<?php echo $this->getUrl().'cancellation-return-exchange-and-refund-policy'?>"
            },
            "Zigly_Sales/js/tag": {
                "reviewurl" : "<?php echo $this->getUrl().'groomerreview/groomerreview/tag'?>"
            },
            "Zigly_Sales/js/invoice": {
                "invoiceBookingUrl" : "<?php echo $this->getUrl().'sales/orders/invoicebooking'?>"
            },
            "Zigly_Sales/js/popup": {
                "title" : "Rate your experience with the Groomer"
            }
        }
    }
</script>