<?php $managepetscolln = $block->getaccountManagepetsCollection(); ?>
<?php $genders = $this->getGenders();?>
<?php $placeholderimage = $block->getplaceholderimage();?>
<?php if ($managepetscolln->getSize() > 0): ?>
    <div class="amtheme-content">
    <?php foreach ($managepetscolln as $pet): ?>
        <div class="amtheme-address-card amtheme-address-billing">
            <div class="amtheme-wrapper">
                <address class="amtheme-content">
                    <?php if($pet->getFilepath()){ ?>
                    <?php $avatarUrl = $block->getPetAssetImage($pet->getFilepath());
                        $avatarImg = explode("/", $pet->getFilepath());
                        if ($avatarImg[0] == 'images'){
                            $imageurl = $avatarUrl;
                        } else {
                            $imageurl = $block->getPetimage($pet->getFilepath());
                        }?>
                    <?php } else { ?>
                    <?php $imageurl = $placeholderimage;?>
                    <?php } ?>
                    <p><img src="<?= $block->escapeUrl($imageurl) ?>" alt="<?= $block->escapeHtml($pet->getName()) ?>" width="50" height="50"/></p>
                    <p class="name"><strong><?= $block->escapeHtml($pet->getName()) ?></strong></p>
                    <p>
                        <span>
                            <?= $block->escapeHtml($pet->getBreedname()) ?>
                        </span>
                        <?php if ($pet->getPetDob() != null){ ?>
                            <span><?= /* @noEscape */ $block->escapeHtml($this->getDob($pet->getPetDob())) ?></span>
                        <?php } else { ?>
                            <span></span>
                        <?php } ?>
                    </p>
                    <p>
                        <span><?= $block->escapeHtml($pet->getAgeYear())." "."years"?></span>
                        <span><?= $block->escapeHtml($pet->getAgeMonth())." "."months"?></span>
                    </p>
                </address>
            </div>
            <div class="amtheme-actions">
                <a class="action edit"
                   title="<?= $block->escapeHtml(__('Edit')) ?>"
                   href="<?= $block->escapeUrl($this->getUrl('managepets/index/form',['id'=>$pet->getId()])) ?>">
                    <?= $block->escapeHtml(__('Edit')) ?>
                </a>  <a class="action delete delete_pet" pet_id="<?= $pet->getId();?>"
                   title="<?= $block->escapeHtml(__('Delete')) ?>"
                   href="javascript:;">
                    <?= $block->escapeHtml(__('Delete')) ?>
                </a>
            </div>
        </div>
    <?php endforeach; ?>
    </div>


<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_Managepets/js/managepetslist": {
                "deleteurl" : "<?= $this->getUrl().'managepets/index/delete'?>"
            }
        }
    }
</script>
<?php else: ?>
<p class="empty">You have no pet entries in your account.</p>
<?php endif ?>
