<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_Sales
 */
$bookingDetails = $block->getBookingDetails();
$startHr = $block->getStartHr();
$startMin = $block->getStartMin();
$endHr = $block->getEndHr();
$endMin = $block->getEndMin();
$startTime = $startHr.':'.$startMin;
?>
<?php if (empty($startHr) || empty($startMin) || empty($endHr) || empty($endMin)) : ?>
    <div class="nodata-msg message-notice notice message">
        <?= __('Something went wrong. Please contact us.') ?>
    </div>
<?php else : ?>
<?php
$startTime = $startHr.':'.$startMin;
if ($endHr <= 12) {
    $endTime = $endHr.':'.$endMin.' am';
} else {
    $endTime = ((int)$endHr - 12).':'.$endMin.' pm';
}
?>

<div class="reschedule-container-main" id="reschedule-container" data-id="<?= $bookingDetails->getEntityId() ?>">
    <input type="hidden" name="selected_date">
    <input type="hidden" name="selected_time">
    <div class="title">
        <?= __('Reschedule') ?>
    </div>
    <div class="actions">
        <div class="primary">
            <a class="action primary" id="submit-schedule" title="Save"><?= __('Save') ?></a>
        </div>
    </div>
    <div class="calender-date-day-selection">
        <div class="grooming-calendar">
            <div class="selection-note"><?= __('Note: Date will be selectable for next 7 days') ?></div>
            <div id="grooming-calendar-slot"></div>
        </div>
        <div id="grooming-timeslot">
            <div class="title"><?= __('Select Time') ?></div>
            <ol name='slots'>
                <?php
                $time = $startTime;
                while ($time) {
                    $prev = date('g:i a', strtotime($time));
                    $next = strtotime('+30mins', strtotime($time));
                    $time = date('g:i a', $next);
                    echo "<li class=\"slot-time\" data-slot=\"$prev\">$prev</li>";
                    if ($prev == ($endTime)) {
                    // if ($prev == ('8:30'.' pm')) {
                        break;
                    }
                }
                ?>
            </ol>
        </div>
    </div>
</div>
<?php
$now = new \DateTime('now', new \DateTimeZone('Asia/Kolkata'));
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_Sales/js/reschedule": {
                "endTime" : "<?= $endTime ?>",
                "startHr" : "<?= $startHr ?>",
                "endHr" : "<?= $endHr ?>",
                "endMin" : "<?= $endMin ?>",
                "serverTime" : "<?= $now->format('Y-m-d H:i:s') ?>"
            }
        }
    }
</script>
<?php endif; ?>
