<?php $reviewDetails = $this->getReviewDetails(); ?>
<div class="admin__field feedback_tag">
    <div class="admin__field-label" >
		<label class="label admin__field-label" for="feedback">
			<span>Professional</span>
		</label>
	</div>
    <div class="admin__field-control control">
    	<div id="feedback" class="control-value admin__field-value">
	    	<a href="<?= $this->getUrl('zigly_groomer/groomer/edit', array('groomer_id' => $reviewDetails['groomer_id'])) ?>">
		    	<?= $reviewDetails['groomer_name'] ?>
            </a>
	    </div>
    </div>
</div>
<div class="admin__field feedback_tag">
    <div class="admin__field-label" >
		<label class="label admin__field-label" for="feedback">
			<span>Service</span>
		</label>
	</div>
    <div class="admin__field-control control">
    	<div id="feedback" class="control-value admin__field-value">
	    	<?= $reviewDetails['service'] ?>
	    </div>
    </div>
</div>
<div class="admin__field feedback_tag">
    <div class="admin__field-label" >
		<label class="label admin__field-label" for="feedback">
			<span>Plan</span>
		</label>
	</div>
    <div class="admin__field-control control">
    	<div id="feedback" class="control-value admin__field-value">
	    	<?= $reviewDetails['plan'] ?>
	    </div>
    </div>
</div>
<div class="admin__field feedback_tag">
    <div class="admin__field-label" >
		<label class="label admin__field-label" for="feedback">
			<span>Order Id</span>
		</label>
	</div>
    <div class="admin__field-control control">
    	<div id="feedback" class="control-value admin__field-value">
    		<?php $orderDetails = $block->getOrderDetails(); ?>
	    	<a href="<?= $orderDetails['url'] ?>">
                <?= $orderDetails['increment_id'] ?>
            </a>
	    </div>
    </div>
</div>
<div class="admin__field feedback_tag">
    <div class="admin__field-label" >
		<label class="label admin__field-label" for="feedback">
			<span>Customer</span>
		</label>
	</div>
    <div class="admin__field-control control">
    	<div id="feedback" class="control-value admin__field-value">
	    	<a href="<?= $this->getUrl('customer/index/edit', array('id' => $reviewDetails['customer_id'])) ?>">
		    	<?= $reviewDetails['customer_name'] ?>
            </a>
	    </div>
    </div>
</div>
<div class="admin__field feedback_tag">
    <div class="admin__field-label" >
		<label class="label admin__field-label" for="feedback">
			<span>Star Rating</span>
		</label>
	</div>
    <div class="admin__field-control control">
    	<div id="feedback" class="control-value admin__field-value">
	    	<div class="nested product-review-table" id="product-review-table">
               	<div class="choice review-field-rating">
                  	<div class="rating-stars-block">
	                    <input type="radio" <?php if ($reviewDetails['star_rating'] == 1) { echo 'checked';}?> id="Feedback_1" value="<?= $reviewDetails['star_rating'] ?>" class="radio">
	                    <label class="rating-star rating-1" for="Feedback_1" title="<?= $reviewDetails['star_rating'] ?> stars" id="Feedback_1_label">
	                    </label>
	                    <input type="radio" <?php if ($reviewDetails['star_rating'] == 2) { echo 'checked';}?> id="Feedback_2" value="<?= $reviewDetails['star_rating'] ?>" class="radio">
	                    <label class="rating-star rating-2" for="Feedback_2" title="<?= $reviewDetails['star_rating'] ?> stars" id="Feedback_2_label">
	                    </label>
	                    <input type="radio" <?php if ($reviewDetails['star_rating'] == 3) { echo 'checked';}?> id="Feedback_3" value="<?= $reviewDetails['star_rating'] ?>" class="radio">
	                    <label class="rating-star rating-3" for="Feedback_3" title="<?= $reviewDetails['star_rating'] ?> stars" id="Feedback_3_label">
	                    </label>
	                    <input type="radio" <?php if ($reviewDetails['star_rating'] == 4) { echo 'checked';}?> id="Feedback_4" value="<?= $reviewDetails['star_rating'] ?>" class="radio">
	                    <label class="rating-star rating-4" for="Feedback_4" title="<?= $reviewDetails['star_rating'] ?> stars" id="Feedback_4_label">
	                    </label>
	                    <input type="radio" <?php if ($reviewDetails['star_rating'] == 5) { echo 'checked';}?> id="Feedback_5" value="<?= $reviewDetails['star_rating'] ?>" class="radio">
	                    <label class="rating-star rating-5" for="Feedback_5" title="<?= $reviewDetails['star_rating'] ?> star" id="Feedback_5_label">
	                    </label>
                  	</div>
               	</div>
            </div>
	    </div>
    </div>
</div>
<div class="admin__field feedback_tag">
    <div class="admin__field-label" >
		<label class="label admin__field-label" for="feedback">
			<span>Feedback Tag</span>
		</label>
	</div>
    <div class="admin__field-control control">
    	<div id="feedback" class="control-value admin__field-value">
	    	<?= $this->getFeedbackTag() ?>
	    </div>
    </div>
</div>
<script type="text/javascript">
	require(['jquery'],function($){
		$(document).ready(function(){
			let checked = $('input[type="radio"]:checked').val();
			$('input[type="radio"]:checked').prevAll('.rating-star').addClass('checked');
		});
	});
</script>