<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_ThankYouPage
 */

namespace Amasty\ThankYouPage\Api;

interface ConfigCreateAccountInterface extends ConfigCustomInterface
{

    /**
     * @return bool
     */
    public function isPasswordAutoGenerated();

    /**
     * @return bool
     */
    public function isEmailFieldVisible();

    /**
     * @return bool
     */
    public function isTermsAndConditionsVisible();

    /**
     * @return string
     */
    public function getTermsText();
}
