<?php
$editAddress = $block->getEditAddress();
?>
<?php if (!$editAddress) : ?>
    <div class="pin-point maps-container" id="maps-container" style="height: 200px">
    </div>
<?php endif; ?>
<?php
$nameBlock = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name');
$telephoneBlock = $block->getLayout()->createBlock('Zigly\Login\Block\Widget\Telephone');
?>
<form class="form groom-wrapper form-address-edit" id="address-popup-form" method="post" action="javascript:;" novalidate="novalidate" enctype="multipart/form-data" data-hasrequired="* Required Fields" data-mage-init='{"validation":{}}'autocomplete="off">
    <div class="legend"><?= __('Address')?></div>
    <div class="popup-form-wrapper">
        <fieldset class="fieldset">
            <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
            <?php if ($editAddress) : ?>
                <input type="hidden" name="id" value="<?= $editAddress->getEntityId() ?>">
            <?php endif; ?>
            <input type="hidden" name="success_url" value="">
            <input type="hidden" name="error_url" value="">
            <div class="fields -double">
                <div class="field field-name-firstname">
                    <div class="control">
                        <?php if ($editAddress) : ?>
                            <input type="text" id="firstname" name="firstname" placeholder="Enter Your First Name *" value="<?= $editAddress->getFirstname() ?>" title="First Name" class="input-text required-entry" data-validate="{required:true}">
                        <?php else: ?>
                            <input type="text" id="firstname" name="firstname" placeholder="Enter Your First Name *" value="<?= $telephoneBlock->getFirstname() ?>" title="First Name" class="input-text required-entry" data-validate="{required:true}">
                        <?php endif; ?>
                        
                    </div>
                </div>
                <div class="field field-name-lastname required">
                    <div class="control">
                        <?php if ($editAddress) : ?>
                            <input type="text" id="lastname" placeholder="Enter Your Last Name *" name="lastname" value="<?= $editAddress->getLastname() ?>" title="Last Name" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
                        <?php else: ?>
                            <input type="text" id="lastname" placeholder="Enter Your Last Name *" name="lastname" value="<?= $telephoneBlock->getLastname() ?>" title="Last Name" class="input-text required-entry" data-validate="{required:true}" aria-required="true">
                        <?php endif; ?>
                        
                    </div>
                </div>
                <div class="field telephone required">
                    <div class="control">
                        <?php if ($editAddress) : ?>
                            <input type="tel" name="telephone" id="telephone" value="<?= $editAddress->getTelephone() ?>" title="Phone Number" placeholder="Enter Your Mobile Number *" class="input-text validate-number required-entry minimum-length-10 maximum-length-10" maxlength="10" data-msg-validate-length="Please enter a 10 digit mobile number." aria-required="true" data-validate="{required:true, 'validate-length':true}" autocomplete="off" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');">
                        <?php else: ?>
                            <input type="tel" name="telephone" id="telephone" value="<?= is_null($telephoneBlock->getTelephone()) ? $telephoneBlock->getcustomerphonenumber() : $telephoneBlock->getTelephone() ?>" title="Phone Number" placeholder="Enter Your Mobile Number *" class="input-text validate-number required-entry minimum-length-10 maximum-length-10" maxlength="10" data-msg-validate-length="Please enter a 10 digit mobile number." oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');" aria-required="true" data-validate="{required:true, 'validate-length':true}"  autocomplete="off">
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="field street required">
                <div class="control">
                    <?php if ($editAddress) : ?>
                        <?php $street = $editAddress->getStreet(); ?>
                        <input type="text" name="street[]" value="<?= $street['0'] ?>" title="Street Address" placeholder="Street Address *" id="street_1" class="input-text required-entry" aria-required="true">
                        <div class="nested">
                            <div class="field additional">
                                <div class="control">
                                    <input type="text" name="street[]" value="<?= isset($street['1']) ? $street['1'] : '' ?>" title="Street Address 2" placeholder="Street Address 2" id="street_2" class="input-text " aria-required="true">
                                </div>
                            </div>
                        </div>
                    <?php else: ?>
                        <input type="text" name="street[]" value="" title="Street Address" placeholder="Street Address *" id="street_1" class="input-text required-entry" aria-required="true">
                        <div class="nested">
                            <div class="field additional">
                                <div class="control">
                                    <input type="text" name="street[]" value="" title="Street Address 2" placeholder="Street Address 2" id="street_2" class="input-text " aria-required="true">
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <?php
                $regions = $block->getRegionCollection();
            ?>
            <div class="fields -double">
                <div class="field city required">
                    <div class="control">
                        <?php if ($editAddress) : ?>
                            <input type="text" name="city" value="<?= $editAddress->getCity() ?>" title="City" placeholder="City *" class="input-text required-entry" id="city" aria-required="true">
                        <?php else: ?>
                            <input type="text" name="city" value="" title="City" placeholder="City *" class="input-text required-entry" id="city" aria-required="true">
                        <?php endif; ?>
                    </div>
                </div>
                <div class="field region required">
                    <div class="control">
                        <select id="region_id" name="region_id" title="State/Province" class="validate-select region_id required-entry" aria-required="true" defaultvalue="0">
                            <option value=""><?= __('Please select a region, state or province.') ?></option>
                            <?php if ($editAddress) : ?>
                                <?php foreach ($regions as $region) : ?>
                                    <?php if ($editAddress && ($editAddress->getRegionId() == $region['region_id'])) : ?>
                                        <option value="<?= $region['region_id'] ?>" selected><?= $region['name'] ?></option>
                                    <?php else: ?>
                                        <option value="<?= $region['region_id'] ?>"><?= $region['name'] ?></option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <?php foreach ($regions as $region) : ?>
                                    <option value="<?= $region['region_id'] ?>"><?= $region['name'] ?></option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </select>
                        <input type="text" id="region" name="region" value="" title="State/Province" class="input-text validate-not-number-first" aria-required="true" style="display: none;">
                    </div>
                </div>
                <div class="field zip required">
                    <div class="control">
                        <?php if ($editAddress) : ?>
                            <input type="text" name="postcode" value="<?= $editAddress->getPostcode() ?>" title="Zip/Postal Code" placeholder="Enter your 6 digit Postal Code *" id="zip" class="input-text validate-number minimum-length-6 maximum-length-6 required-entry" data-validate="{'validate-length':true}" data-msg-validate-length="Please enter a 6 digit Postal Code." oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');" maxlength="6" aria-required="true">
                        <?php else: ?>
                            <input type="text" name="postcode" value="" title="Zip/Postal Code" placeholder="Enter your 6 digit Postal Code *" id="zip" class="input-text validate-number minimum-length-6 maximum-length-6 required-entry" data-validate="{'validate-length':true}" data-msg-validate-length="Please enter a 6 digit Postal Code." oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');" maxlength="6" aria-required="true">
                        <?php endif; ?>
                        <div role="alert" class="message warning" style="display:none">
                            <span></span>
                        </div>
                    </div>
                </div>
                <div class="field country required">
                    <div class="control">
                        <input type="hidden" name="country_id" value="IN">
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action save primary" id="save-service-address" data-action="save-address" aria-label="Save Address" title="Save Address">
                    <?= __('SAVE') ?>
                </button>
            </div>
        </div>
    </div>
</form>