<?php
$customerAddress = $block->getAddressCollection();
?>
<?php if (count($customerAddress)): ?>
<ul class="manage-detail">
    <?php foreach ($customerAddress as $address): ?>
        <li class="detail-listing">
            <div class="detail-wrapper">
                <input type="hidden" name="select_detail" id="select-detail_<?= $address['hub_id'] ?>" >
                <label for="select-detail_<?= $address['hub_id'] ?>"></label>
                <span class="detail-content">
                    <p class="street"><?= $address['location']?></p>
                    <p class="street"><?= $address['street_one']?><?= ($address['street_two']) ? ', '.$address['street_two']: '' ?></p>
                    <p>
                        <span><?= $address['state']." - ".$address['pincode'];?></span>
                    </p>
                    <p><?= $address['availability_info']?></p>
                </span>
            </div>
            <div class="action-address">
                <button class="select-address-action" value="<?= $address['hub_id'] ?>" id="select-address-<?= $address['hub_id'] ?>">Select</button>
            </div>
        </li>
    <?php endforeach; ?>
</ul>
<?php else : ?>
    <div class="nodata-msg message-notice notice message"><?= __('No Centers available for your selected location.') ?></div>
<?php endif; ?>
