<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_GroomingService
 */
$managepetscolln = $block->getaccountManagepetsCollection();
$genders = $this->getGenders();
$placeholderimage = $this->getplaceholderimage();
$customerAddress = $block->getAddressCollection();
$plansCollection = $block->getPlans();
$startHr = $block->getStartHr();
$startMin = $block->getStartMin();
$endHr = $block->getEndHr();
$endMin = $block->getEndMin();
$startTime = $startHr.':'.$startMin;
$startTime = $startHr.':'.$startMin;
if ($startHr <= 12) {
    $startTimes = $startHr.':'.$startMin.' am';
} else {
    $startTimes = ((int)$startHr - 12).':'.$startMin.' pm';
}
if ($endHr <= 12) {
    $endTime = $endHr.':'.$endMin.' am';
} else {
    $endTime = ((int)$endHr - 12).':'.$endMin.' pm';
}
?>
<?php if (!count($customerAddress)): ?>
    <div class="nodata-msg message-notice notice message"><?= __('No Centers available for your selected location.') ?></div>
<?php endif; ?>
<?php if (!count($plansCollection)): ?>
    <div class="nodata-msg message-notice notice message"><?= __('No Plans available for your selected location.') ?></div>
<?php endif; ?>
<div id="groomer-service">
    <div class="progress-steps-section">
        <div class="service-location">
            <a href="<?php echo $this->getUrl('services/pet-grooming/experience')?>" class="nav-back"><img src="<?php echo $this->getViewFileUrl('Zigly_GroomingService::images/nav-back.png'); ?>"></a>
            <p class="service-name">Pet Grooming <span class="location">(Currently serving Delhi NCR)</span></p>
        </div>

        <ul id="progressbar" class="grooming-container-width">
            <li class="active">
                <div class="steps">
                    <div class="step-name">
                        <span class="selected-pet">Select Pet(s)</span>
                    </div>
                </div>
            </li>
            <li>
                <div class="steps">
                    <div class="step-name">
                        <span class="selected-plan">Select Plan</span>
                    </div>
                </div>
            </li>
            <li>
                <div class="steps"><div class="step-name"><span class="selected-time">Select Time Slot</span></div></div>
            </li>
            <li>
                <div class="steps"><div class="step-name"><span class="selected-address">Select Center</span></div></div>
            </li>
            <li>
                <div class="steps last"><div class="step-name"><span>Review Booking</span></div></div>
            </li>
            <?php /* 
            <label for="back" class="back-nav" style="display: none;">
                <input type="button" name="back" class="back action-button" value="Back"/>
            </label>
            <?php if (count($customerAddress) && count($plansCollection)): ?>
            <label for="Next" class="next-nav">
                <input type="button" name="next" class="next action-button" value="Next" />
            </label>
            <?php endif; ?>*/?>
        </ul>
    </div>
    <fieldset class="field1 current grooming-container-width">
        <div class="groom-title"><?= $block->escapeHtml(__('Select a pet you want groomed: ')) ?></div>
            <ul class="manage-pets">
                <?php if ($managepetscolln->getSize() > 0): ?>
                    <?php foreach ($managepetscolln as $pet): ?>
                        <li class="pet-listing <?= $block->escapeHtml(__($pet->getId())) ?>">
                            <div class="pet-actions">
                                <a class="action edit" title="<?= $block->escapeHtml(__('Edit')) ?>" href="<?php echo $this->getUrl('managepets/index/form',['id'=>$pet->getId(), 'destination'=>'grooming', 'service'=>'center']);?>">
                                    <?= $block->escapeHtml(__('Edit |')) ?>
                                </a>
                                <a class="action delete delete_pet" pet_id="<?=$pet->getId();?>" title="<?= $block->escapeHtml(__('Delete')) ?>" href="javascript:;">
                                    <?= $block->escapeHtml(__('Delete')) ?>
                                </a>
                            </div>
                            <div class="pet-wrapper">
                                <input type="hidden" name="select_pet" id="select-pet-<?= $pet->getId();?>" >
                                <label for="select-pet-<?= $pet->getId();?>">
                                </label>
                                <span class="pet-content">
                                    <?php if($pet->getFilepath()){ ?>
                                        <?php $avatarUrl = $this->getPetAssetImage($pet->getFilepath());
                                        $avatarImg = explode("/", $pet->getFilepath());
                                        if ($avatarImg[0] == 'images'){
                                            $imageurl = $avatarUrl;
                                        } else {
                                            $imageurl = $this->getPetimage($pet->getFilepath());
                                        }?>
                                    <?php } else { ?>
                                        <?php $imageurl = $placeholderimage;?>
                                    <?php } ?>
                                    <p><img src="<?= $block->escapeUrl($imageurl) ?>" alt="<?= $block->escapeHtml($pet->getName()) ?>" width="50" height="50"/></p>
                                    <p class="name"><strong><?= $block->escapeHtml($pet->getName()) ?></strong></p>
                                    <p class="breedname">
                                        <span><?= $block->escapeHtml($pet->getBreedname()) ?></span>
                                    </p>
                                    <p style="display:none;">
                                        <?php if ($pet->getPetDob() != null){ ?>
                                            <span><?= /* @noEscape */ $block->escapeHtml($this->getDob($pet->getPetDob())) ?></span>
                                        <?php } else { ?>
                                            <span></span>
                                        <?php } ?>
                                    </p>
                                    <p>
                                        <span><?= $block->escapeHtml($pet->getAgeYear())." "."years"?></span>
                                        <span><?= $block->escapeHtml($pet->getAgeMonth())." "."months"?></span>
                                    </p>
                                </span>
                            </div>
                            <div class="action-pet">
                                <button class="select-pet-action" value="<?= $pet->getId();?>" id="select-pet-<?= $pet->getId();?>">Select</button>
                            </div>
                        </li>
                    <?php endforeach; ?>
                <?php endif; ?>
                <li class="pet-listing">
                    <div class="add-pet">
                        <a class="action edit" title="<?= $block->escapeHtml(__('Add New Pet')) ?>" href="<?php echo $this->getUrl('managepets/index/form',['destination'=>'grooming', 'service'=>'center'])?>">
                            <?= $block->escapeHtml(__('Add New Pet')) ?>
                        </a>
                    </div>
                </li>
            </ul>

            <!-- Pet images -->
            <div class="pet-images">
                <div class="left-side-pet">
                    <img src='<?php echo $this->getViewFileUrl('Zigly_GroomingService::images/appointment_cat.png'); ?>' alt="Cat" />
                </div>
                <div class="right-side-pet">
                    <img src='<?php echo $this->getViewFileUrl('Zigly_GroomingService::images/appointment_dogs_cat.png'); ?>' alt="Dog and Cat" />
                </div>
            </div>
    </fieldset>
    <fieldset class="field2 grooming-container-width">
    </fieldset>
    <fieldset class="field3 grooming-container-width">
        <input type="hidden" name="seleted_date">
        <input type="hidden" name="seleted_time">
            <!--<div class="plan-booked">
                 <div class="booked-content">
                    <h5 class="booked-pet-name">Jackson</h5>
                    <p class="plan-duration-booked">
                        <span class="booked-plan">custom plan</span>
                        <span class="booked-duration">180 Mins</span>
                    </p>
                </div> 
            </div>-->

        <div class="calender-date-day-selection">
            <div class="grooming-calendar">
                <div class="selection-note"><?= __('Note: Date will be selectable for next 7 days') ?></div>
                <div id="grooming-calendar-slot">
                </div>
            </div>
            <div id="grooming-timeslot">
                <div class="title"><?= __('Select Time') ?></div>
                <div class="slot-notes">
                    <div class="slots avail"><?= __('Slots Available') ?></div>
                    <div class="slots full"><?= __('Slots Full') ?></div>
                </div>
                <ol name='slots'>
                    <?php
                    $time = $startTime;
                    while ($time) {
                        $prev = date('g:i a', strtotime($time));
                        $next = strtotime('+30mins', strtotime($time));
                        $time = date('g:i a', $next);
                        echo "<li class=\"slot-time\" data-slot=\"$prev\">$prev</li>";
                        if ($prev == ($endTime)) {
                            break;
                        }
                    }
                    ?>
                </ol>
                <div class="slot-proceed">
                    <button class="time-proceed" value="" id="time-proceed-73" disabled>Proceed</button>
                </div>
            </div>
        </div>
    </fieldset>
    <fieldset class="field4 grooming-container-width">
        <div class="address-list">
        </div>
        <!-- Pets image -->
        <div class="pets-image">
            <div class="address-pet">
                <img src='<?php echo $this->getViewFileUrl('Zigly_GroomingService::images/address_selection.png'); ?>' alt="Address Selection" />
            </div>
        </div>
        <div id="address-modal" style="display:none;"></div>
        <div id="address-edit-modal" style="display:none;"></div>
    </fieldset>
    <fieldset class="field5 grooming-full-width">
    </fieldset>
</div>
<?php
$now = new \DateTime('now', new \DateTimeZone('Asia/Kolkata'));
?>
<script type="text/javascript">
    require([
    'jquery',
    'domReady!'
    ], function($){

        $(document).on('click', '.view-plan-details',function(){
            // Replace the text when it's opened
            $(this).text(function(){
                if ($(this).text() == 'Select Service'){
                    return 'Select Services';
                }else{
                    return 'Select Services';
                }
            });
            // $(this).siblings('.detail-options').toggle();
        });
        $(document).on('click', '.view-plan-details-include',function(){
            // Replace the text when it's opened
            $(this).text(function(){
                if ($(this).text() == "What's included"){
                    return "What's included:";
                }else{
                    return "What's included:";
                }
            });
            // $(this).siblings('.detail-options').toggle();
        });
         $(document).on('click','.list-open',function(){
            $('.list-open').find('i.fa-angle-down').css({'transform': ''});
            $(this).find('i.fa-angle-down').css({'transform': 'rotate(-180deg)'});
            if($(this).next().hasClass('show')){
                $(this).next().removeClass('show');
                $(this).next().slideUp();
                $(this).find('i.fa-angle-down').css({'transform': ''});
            }else{
                $(this).parent().parent().find('li .list-details').removeClass('show');
                $(this).parent().parent().find('li .list-details').slideUp();
                $(this).next().toggleClass('show');
                $(this).next().slideToggle();
            }
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_GroomingService/js/groomservicecenter": {
                "getplan" : "<?php echo $this->getUrl().'services/experiencegrooming/getplans'?>",
                "endTime" : "<?= $endTime ?>",
                "startTime" : "<?= $startTimes ?>",
                "startHr" : "<?= $startHr ?>",
                "startMin" : "<?= $startMin ?>",
                "endHr" : "<?= $endHr ?>",
                "endMin" : "<?= $endMin ?>",
                "serverTime" : "<?= $now->format('Y-m-d H:i:s') ?>",
                "currencysymbol" : "<?php echo $block->currencySymbol() ?>"
            }
        }
    }
</script>
<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_Managepets/js/managepetslist": {
                "deleteurl" : "<?php echo $this->getUrl().'managepets/index/delete'?>"
            }
        }
    }
</script>
<script type="text/javascript">
    require([
    'jquery',
    ], function($){
        $(document).ready(function(){
            if ($(".grooming-container-width#progressbar li:nth-child(4)").hasClass("active")) {
                alert('hi');
            };
        });
        });
</script>