<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_Managepets
 */
?>
<?php $petdetails = $this->getpetdetails();?>
<?php $types = $this->getSpecies($petdetails->getType());?>
<?php $breeds = $this->getBreeds($petdetails->getType(),$petdetails->getBreed());?>
<?php $genders = $this->getGenders();?>
<?php $jsondata = $this->encodebreed($breeds->getData()); ?>
<form data-mage-init='{"validation": {}}' class="form" id="managepet-form" method="post" autocomplete="off">
  <input type='hidden' name='customer_id' value="<?php echo $block->getCustomerId();?>"/>
  <input type="hidden" name="pet_id" value=<?php echo $petdetails->getId();?> />
  <fieldset class="admin__fieldset">
      <div class="admin__field _required">
        <label class="admin__field-label" for="type"><span><?php echo __('Type') ?></span></label>
        <div class="admin__field-control">
            <select id="type" name="type" title="Type" class="admin__control-select validate-select type required-entry" aria-required="true">
                <?php foreach($types as $tkey => $type){ ?>
                <?php $selected = ($petdetails->getType() == $type->getSpeciesId())? 'selected':'';?>
                <option value="<?php echo $type->getSpeciesId();?>" <?php echo $selected;?>><?php echo $type->getName();?></option>
                <?php }?>
            </select>
        </div>
      </div>
      <div class="admin__field _required">
        <label class="admin__field-label" for="type"><span><?php echo __('Gender') ?></span></label>
        <div class="admin__field-control">
            <select id="gender" name="gender" title="gender" class="admin__control-select validate-select type required-entry" aria-required="true">
                <?php foreach($genders as $gkey => $gender){ ?>
                <?php $selected = ($petdetails->getGender() == $gkey)? 'selected':'';?>
                <option value="<?php echo $gkey;?>" <?php echo $selected;?>><?php echo $gender;?></option>
                <?php }?>
            </select>
        </div>
      </div>
      <div class="admin__field _required">
        <label class="admin__field-label" for="type"><span><?php echo __('Breed') ?></span></label>
        <div class="admin__field-control">
           <input type="hidden" name="breed" id="breed_id" value="<?php echo $petdetails->getBreed();?>"/>
            <?php
              $bname = '';
              if($petdetails->getBreed()){
                $bname = $this->getbreeddata($petdetails->getBreed());
              }
            ?>
            <input type="text" name="breedname" id="breedname" value="<?php echo $bname;?>" title="<?php echo __('Breedname') ?>" data-mage-init='{"breed-search":{"breeddata" : <?php echo $jsondata;?>}}' class="admin__control-text" placeholder="Breed" data-validate="{required:true,breedvalidation:true}">
        </div>
      </div>
      <div class="admin__field _required">
            <label class="admin__field-label" for="pet_dob">
                <?php echo __('DOB'); ?>
            </label>
            <div class="admin__field-control">
              <input type="text" id="pet_dob" class="admin__control-text" data-validate="{'required':true,'validate-no-utf8mb4-characters':true,'currentdateMethod':true,
                'validate-date':{'dateFormat':'y\/MM\/dd'},'validate-dob':{'dateFormat':'y\/MM\/dd'}}" name="pet_dob" data-selector="pet_dob" value="<?php echo $this->getDobvalue($petdetails->getPetDob());?>" aria-required="true" autocomplete="off">
            </div>
        </div>
      <div class="admin__field _required">
          <label for="name" class="admin__field-label"><span><?php echo __('Age(Year)') ?></span></label>
          <div class="admin__field-control">
              <input type="number" name="age_year" id="age_year" value="<?php echo $petdetails->getAgeYear();?>" title="<?php echo __('Year') ?>" class="admin__control-text" data-validate="{required:true}" readonly>
          </div>
      </div>
      <div class="admin__field _required">
          <label for="name" class="admin__field-label"><span><?php echo __('Age(Month)') ?></span></label>
          <div class="admin__field-control">
              <input type="number" name="age_month" id="age_month" value="<?php echo $petdetails->getAgeMonth();?>" title="<?php echo __('Year') ?>" class="admin__control-text" data-validate="{required:true}" readonly>
          </div>
      </div>
      <div class="admin__field _required">
          <label for="name" class="admin__field-label"><span><?php echo __('Name') ?></span></label>
          <div class="admin__field-control">
              <input type="text" name="name" id="name" value="<?php echo $petdetails->getName();?>" title="<?php echo __('Name') ?>" class="admin__control-text" data-validate="{required:true}">
          </div>
      </div>
      <div class="admin__field">
        <label for="name" class="admin__field-label"><span><?php echo __('Select Photo') ?></span></label>
        <div class="admin__field-control">
          <?php $imagdis = ''; ?>
           <?php if($petdetails->getFilepath()){ ?>
              <?php $imagespath = explode(",",$petdetails->getFilepath());?>
              <?php if(!empty($imagespath)){ ?>
                <?php foreach($imagespath as $ikey => $pathurl){ ?>
                    <?php if($pathurl){ ?>
                      <?php $imagdis = 'style="display:none"'; ?>
                      <div class="image item" data-role="image" id="imagecustomdiv">
                          <div class="product-image-wrapper">
                              <input type="hidden" accept="image/jpeg, image/png, image/jpg," name="filedatas[]" value="<?php echo $pathurl;?>">
                              <img class="product-image" data-role="image-element" src="<?php echo $this->getPetimageurl($pathurl);?>" alt="">
                              <div class="actions">
                                  <div class="tooltip">
                                      <button type="button" class="action-remove" data-role="delete-button" title="Delete image">
                                          <span>
                                              Delete image
                                          </span>
                                      </button>
                                  </div>
                              </div>
                          </div>
                      </div>
                    <?php break;?>
                    <?php }?>
                <?php }?>
              <?php } ?>
          <?php }?>
          <div class="image image-placeholder" id="imageappend" <?php echo $imagdis;?>>
            <div class="uploader">
                  <div class="fileinput-button form-buttons button">
                      <span>Browse Files...</span>
                      <input id="fileupload" type="file" name="image">
                  </div>
                  <div class="clear"></div>
              </div>
              <div class="product-image-wrapper">
                  <p class="image-placeholder-text">Browse to find or drag image here</p>
              </div>
          </div>
        </div>
      </div>
  </fieldset>
</form>
