<div class="wallet-total">
    <?php $totalBalance = $this->getTotalBalance(); ?>
    <label><?= $block->escapeHtml(__('Wallet Balance : ')) ?></label>
    <label><?= $this->currency(floor($totalBalance)) ?></label>
</div>
<div class="add-wallet-money">
    <button type="button" class="add-wallet-button action-basic" id="add-wallet-button" data-index="add_wallet">
        <span>Add Wallet</span>
    </button>
</div>
<div id="popup-mpdal-wallet" style="display: none;">
    <form class="wallet-form" method="post" action="" id="form-validate" enctype="multipart/form-data"
        data-hasrequired="<?php /* @noEscape */ echo __('*') ?>" data-mage-init='{"validation":{}}'>
        <div id="result"></div>
        <div class="admin__page-section-item-content">
            <div class="admin__page-section-item wallet-history">
                <div class="admin__field choose-amount">
                    <label class="admin__field-label" for="amount"><span><?php /* @noEscape */ echo __('Enter Amount')?></span></label>
                    <div class="admin__field-control">
                        <input type="text" name="amount" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');" id="amount" title="<?php echo __('Enter Amount') ?>" class="input-text" placeholder="<?php echo __('Enter Amount') ?>">
                            <span class = "error">
                    </div>
                    <label class="admin__field-label" for="flag"><span><?php /* @noEscape */ echo __('Credit/Debit')?></span></label>
                    <div class="admin__field-control">
                        <select name="flag" id="flag" >
                            <option value="">Please select</option>
                            <option value="0">Debit</option>
                            <option value="1">Credit</option>
                        </select>
                    </div>
                    <label class="admin__field-label" for="remarks"><span><?php /* @noEscape */ echo __('Enter Remarks')?></span></label>
                    <div class="admin__field-control">
                        <input type="text" name="remarks" id="remarks" title="<?php echo __('Remarks') ?>" class="input-text" placeholder="<?php echo __('Enter Remarks') ?>">
                    </div>
                </div>
                <div class="admin__field">
                    <button class="action primary wallet" id="add-wallet" title="Submit" type="submit">
                        <span><?php /* @noEscape */ echo __('Submit')?></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>