<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_VetConsulting
 */
$managepetscolln = $block->getaccountManagepetsCollection();
$genders = $this->getGenders();
$placeholderimage = $this->getplaceholderimage();
$startHr = $block->getStartHr();
$startMin = $block->getStartMin();
$endHr = $block->getEndHr();
$endMin = $block->getEndMin();
$startTime = $startHr.':'.$startMin;
$startTime = $startHr.':'.$startMin;
if ($endHr <= 12) {
    $endTime = $endHr.':'.$endMin.' am';
} else {
    $endTime = ((int)$endHr - 12).':'.$endMin.' pm';
}
?>
<div id="vet-consulting">
    <ul id="progressbar" class="grooming-container-width">
        <li class="active"><span>Select area</span><span class="mobile-status">1</span></li>
        <li><span>Select Pet</span><span class="mobile-status">2</span></li>
        <li><span>Select Pain Points</span><span class="mobile-status">3</span></li>
        <li><span>Select Time Slot</span><span class="mobile-status">4</span></li>
        <li><span>Select Vet</span><span class="mobile-status">5</span></li>
        <li><span>Review Booking</span><span class="mobile-status">6</span></li>
         <label for="back" class="back-nav" style="display: none;">
            <input type="button" name="back" class="back action-button" value="Back"/>
        </label>
        <label for="Next" class="next-nav">
            <input type="button" name="next" class="next action-button" value="Next" />
        </label>
    </ul>
    <fieldset class="field1 current grooming-container-width">
        <div class="search-area-landmark">
            <input type="text" name="area_landmark" title="Search Area Landmark" placeholder="Search Area Landmark" id="area_landmark" class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off" aria-expanded="false" value="<?= ($block->getLocation()) ? $block->escapeHtml($block->getLocation()) : '' ?>">

            <span class="current-location" id='current-location' >Use my location</span>
        </div>

        <div class="location-pet-image">
            <img src="<?php echo $this->getViewFileUrl('Zigly_VetConsulting::images/select_area.png'); ?>" alt="Location Pet Image">
        </div>
    </fieldset>
    <fieldset class="field2 grooming-container-width">
    </fieldset>
    <fieldset class="field3 grooming-container-width">
    </fieldset>
    <fieldset class="field4 grooming-container-width">
        <input type="hidden" name="selected_date">
        <input type="hidden" name="selected_time">
        <div class="calender-date-day-selection">
            <div class="grooming-calendar">
                <div class="selection-note"><?= __('Note: Date will be selectable for next 7 days') ?></div>
                <div id="grooming-calendar-slot">
                </div>
            </div>
            <div id="grooming-timeslot">
                <div class="title"><?= __('Select Time') ?></div>
                <ol name='slots'>
                    <?php
                    $time = $startTime;
                    while ($time) {
                        $prev = date('g:i a', strtotime($time));
                        $next = strtotime('+30mins', strtotime($time));
                        $time = date('g:i a', $next);
                        echo "<li class=\"slot-time\" data-slot=\"$prev\">$prev</li>";
                        if ($prev == ($endTime)) {
                            break;
                        }
                    }
                    ?>
                </ol>
            </div>
        </div>
    </fieldset>
    <fieldset class="field5 grooming-container-width">
        <!-- Pets image -->
        <div class="pets-image">
            <div class="address-pet">
                <img src='<?php echo $this->getViewFileUrl('Zigly_GroomingService::images/address_selection.png'); ?>' alt="Address Selection" />
            </div>
        </div>
    </fieldset>
    <fieldset class="field6 grooming-full-width">
    </fieldset>
</div>
<script type="text/javascript">
    require([
    'jquery',
    'domReady!'
    ], function($){

        $(document).on('click', '.view-plan-details',function(){
            $(this).siblings('.detail-options').toggle();
        });

         $(document).on('click','.list-open',function(){
            $('.list-open').find('i.fa-angle-down').css({'transform': ''});
            $(this).find('i.fa-angle-down').css({'transform': 'rotate(-180deg)'});
            if($(this).next().hasClass('show')){
                $(this).next().removeClass('show');
                $(this).next().slideUp();
                $(this).find('i.fa-angle-down').css({'transform': ''});
            }else{
                $(this).parent().parent().find('li .list-details').removeClass('show');
                $(this).parent().parent().find('li .list-details').slideUp();
                $(this).next().toggleClass('show');
                $(this).next().slideToggle();
            }
        });
    });
</script>
<?php
$now = new \DateTime('now', new \DateTimeZone('Asia/Kolkata'));
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_VetConsulting/js/vetconsulting": {
                "getpets" : "<?php echo $this->getUrl().'services/vet/getpets'?>",
                "getpainpoints" : "<?php echo $this->getUrl().'services/vet/getpainpoints'?>",
                "settimeslot" : "<?php echo $this->getUrl().'services/vet/settimeslot'?>",
                "getvet" : "<?php echo $this->getUrl().'services/vet/getvet'?>",
                "getvetbyfilter" : "<?php echo $this->getUrl().'services/vet/getvetbyfilter'?>",
                "profileUrl" : "<?php echo $this->getUrl().'services/vet/getvetdetail'?>",
                "reviewVet" : "<?php echo $this->getUrl().'services/vet/reviewvet'?>",
                "timeslot" : "<?php echo $this->getUrl().'services/vet/timeslot'?>",
                "applyWallet" : "<?php echo $this->getUrl().'services/vet/applywallet'?>",
                "removeWallet" : "<?php echo $this->getUrl().'services/vet/removewallet'?>",
                "loadreview" : "<?php echo $this->getUrl().'services/vet/loadreview'?>",
                "applyCoupon" : "<?php echo $this->getUrl().'services/vet/applycoupon'?>",
                "removeCoupon" : "<?php echo $this->getUrl().'services/vet/removecoupon'?>",
                "uploadImageUrl" : "<?php echo $this->getUrl().'services/vet/fileupload'?>",
                "endTime" : "<?= $endTime ?>",
                "startHr" : "<?= $startHr ?>",
                "endHr" : "<?= $endHr ?>",
                "endMin" : "<?= $endMin ?>",
                "serverTime" : "<?= $now->format('Y-m-d H:i:s') ?>",
                "currencysymbol" : "<?php echo $block->currencySymbol() ?>"
            }
        }
    }
</script>