<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_VetConsulting
 */
$painPoints = $this->getPainPoints(); ?>
<div class="select-pain-points">
    <div class="choose-pain-points">
        <label><?= $block->escapeHtml(__('Select Painpoint(s)')) ?></label>
        <div class="pain-points-control type">
            <?php if (!empty($painPoints)): ?>
                <?php foreach($painPoints as $painPoint){ ?>
                    <div class="points">
                        <input type="checkbox" name="pain_points[]" class="primary check-painpoints" id="<?php /* @noEscape */ echo $painPoint ?>" value="<?php /* @noEscape */ echo $painPoint ?>" title="<?php /* @noEscape */ echo $painPoint ?>" >
                        <label class="pain_points-label" for="<?php /* @noEscape */ echo $painPoint ?>">
                            <?php echo $painPoint; ?>
                        </label>
                    </div>
                <?php }?>
            <?php endif; ?>
        </div>
    </div>
    <div class="describe-problem">
        <div class="describe_problem-control type">
            <textarea name="describe_problem" id="describe_problem" title="<?php echo __('Describe your problem') ?>" class="input-text" placeholder="<?php echo __('Describe your problem') ?>" rows="4" cols="15"></textarea>
        </div>
        <form enctype="multipart/form-data">
            <div class="add-image-doc">
                <input type="file" multiple name="image_document[]" id="imageDocUpload" style="display: none;" />
                <a class="action" title="<?= $block->escapeHtml(__('Add Image(s) / Documents')) ?>" id="image-doc" href="javascript:;">
                    <?= $block->escapeHtml(__('Add Image(s) / Documents')) ?>
                </a>
            </div>
        </form>
    </div>
    <div class="uploaded-image-doc">
        <span id="empty-painpoints"></span>
    </div>
</div>