<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_VetConsulting
 */
$managepetscolln = $block->getaccountManagepetsCollection();
$placeholderimage = $this->getplaceholderimage(); ?>
<ul class="manage-pets">
    <?php if ($managepetscolln->getSize() > 0): ?>
        <?php foreach ($managepetscolln as $pet): ?>
            <li class="pet-listing">
                <div class="pet-wrapper">
                    <span class="pet-title">
                        <?php echo $pet->getName(); ?>
                    </span>
                    <input type="radio" name="select_pet" value="<?php echo $pet->getId();?>" id="select-pet-<?= $pet->getId();?>" >
                    <label for="select-pet-<?= $pet->getId();?>">
                    </label>
                    <span class="pet-content">
                        <?php if($pet->getFilepath()){ ?>
                            <?php $avatarUrl = $this->getPetAssetImage($pet->getFilepath());
                            $avatarImg = explode("/", $pet->getFilepath());
                            if ($avatarImg[0] == 'images'){
                                $imageurl = $avatarUrl;
                            } else {
                                $imageurl = $this->getPetimage($pet->getFilepath());
                            }?>
                        <?php } else { ?>
                            <?php $imageurl = $placeholderimage;?>
                        <?php } ?>
                        <p><img src="<?php echo $imageurl?>" alt="<?php echo $pet->getName();?>" width="50" height="50"/></p>
                        <p class="name"><strong><?php echo $pet->getName(); ?></strong></p>
                        <p>
                            <span><?php echo $pet->getBreedname();?></span>
                            <?php if ($pet->getPetDob() != null){ ?>
                                <span><?= /* @noEscape */ $this->getDob($pet->getPetDob()) ?></span>
                            <?php } else { ?>
                                <span></span>
                            <?php } ?>
                        <p>
                            <span><?php echo $pet->getAgeYear()." "."years"?></span>
                            <span><?php echo $pet->getAgeMonth()." "."months"?></span>
                        </p>
                    </span>
                </div>
                <div class="pet-actions">
                    <a class="action edit" title="<?= $block->escapeHtml(__('Edit')) ?>" href="<?php echo $this->getUrl('managepets/index/form',['id'=>$pet->getId(), 'destination'=>'grooming', 'service'=>'vet']);?>">
                        <?= $block->escapeHtml(__('Edit |')) ?>
                    </a>
                    <a class="action delete delete_pet" pet_id="<?=$pet->getId();?>" title="<?= $block->escapeHtml(__('Delete')) ?>" href="javascript:;">
                        <?= $block->escapeHtml(__('Delete')) ?>
                    </a>
                </div>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
    <li class="pet-listing">
        <div class="add-pet">
            <a class="action edit" title="<?= $block->escapeHtml(__('Add New Pet')) ?>" href="<?php echo $this->getUrl('managepets/index/form',['destination'=>'grooming', 'service'=>'vet'])?>">
                <?= $block->escapeHtml(__('Add New Pet')) ?>
            </a>
        </div>
    </li>
</ul>

<!-- Pet images -->
<div class="pet-images">
    <div class="left-side-pet">
        <img src='<?php echo $this->getViewFileUrl('Zigly_GroomingService::images/appointment_cat.png'); ?>' alt="Cat" />
    </div>
    <div class="right-side-pet">
        <img src='<?php echo $this->getViewFileUrl('Zigly_GroomingService::images/appointment_dogs_cat.png'); ?>' alt="Dog and Cat" />
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_Managepets/js/managepetslist": {
                "deleteurl" : "<?php echo $this->getUrl().'managepets/index/delete'?>"
            }
        }
    }
</script>