<?php
$vetSession = $block->getVetSession();
$professional = $block->getProfessionalById($vetSession['vet_id']);
$experience = $professional->getData('year_of_experience');
$experience = ($experience == 0 || $experience == NULL)? '0 years of experience': "$experience years of experience";
$breedTypeName = $block->getBreed();
$vetSession['pet_category'] = $breedTypeName;
$petdetails = $block->getPet();
if (!empty($petdetails)) {
    $vetSession['pet_name'] = $petdetails['name'];
    $vetSession['pet_breed'] = $petdetails['breed'];
    $vetSession['pet_dob'] = $petdetails['pet_dob'];
    $vetSession['pet_gender'] = $petdetails['gender'];
    $vetSession['pet_age'] = $petdetails['age_year'].' years '.$petdetails['age_month'].' months';
    $vetSession['pet_species'] = $petdetails['type'];
    $vetSession['pet_category'] = $breedTypeName;
}
?>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<div class="pets-grooming wrapper progress-sections">
    <div class="pets-grooming-booking-review review-booking">
        <div class="review-booking-wrapper booking">
            <div class="review-booking-left-right selected-vet">
                <div class="vet review-booking-vet-left">
                    <div class="vet-content">
                        <div class="vet-icon">
                           <img src='<?php echo $this->getViewFileUrl('Zigly_VetConsulting::images/vet_avatar.png'); ?>' alt="vet-selection" />
                        </div>
                        <div class="vet-title">
                            <h3 class="title"><?= $block->escapeHtml(__('VIDEO CONSULTING')) ?></h3>
                        </div>
                        <div class="vet-details">
                            <p class="details"><?= $block->escapeHtml(__('Includes Audio, Video and Chat')) ?></p>
                        </div>
                        <div class="vet-price">
                            <?= /* @noEscape */ $block->currency(floor($vetSession['subtotal'])) ?>
                        </div>
                        <div class="plan-view">
                            <div class="views-details">
                                <div class="duration">
                                    <span class="plan-duration"><?= $block->escapeHtml(__('30')) ?><span class="time-formate"><?= __('Mins') ?></span></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="review-booking-right payment-booking">
                    <div class="booking-address">
                        <a href="javascript:;" class="edit-vet-booking">edit</a>
                        <div class="booking-details">
                            <h4 class="date"><?= __('Date: ') ?><span class="date"><?= $block->escapeHtml(__($block->getDate())) ?></span></h4>
                        </div>
                        <div class="booking-details">
                            <?php if (!empty($vetSession['selected_time'])){ ?>
                                <h4 class="time"><?= __('Time: ') ?><span class="time"><?= $block->escapeHtml(__($vetSession['selected_time'])) ?></span></h4>
                            <?php } ?>
                        </div>
                        <div class="booking-details">
                            <span class="vet-name">
                                <strong><?= $block->escapeHtml(__($professional->getName())) ?></strong>
                            </span>
                            <a href="javascript:void(0);" class="view-vet-profile" key="<?= $block->escapeHtml(__($professional->getGroomerId())) ?>"><?= __('view') ?></a></br>
                            <div class="vetnarian-details">
                                <?php if(!empty($professional->getSelectSpecialisation())){ ?>
                                <span class="specialty"><?= $block->escapeHtml(__($professional->getSelectSpecialisation())) ?></span></br>
                                <?php } else { ?>
                                <span class="specialty"><?= $block->escapeHtml(__($professional->getSpecialisationOther())) ?></span></br>
                                <?php } ?>
                                <span class="vet-exp"><?= $block->escapeHtml(__($experience)) ?></span></br>
                                <span class="vet-degree"><?= $block->escapeHtml(__($professional->getCertification())) ?></span>
                            </div>
                        </div>
                    </div>
                    <div class="booking-payment">
                        <div class="booking-amount">
                            <h4 class="amount-text"><?= $block->escapeHtml(__('Consultation Fees')) ?></h4>
                            <?php if (empty($vetSession['wallet_discount_amount']) && empty($vetSession['coupon_discount_amount'])) {
                                    $vetSession['grand_total'] = $vetSession['subtotal'];
                                } ?>
                            <p class="amount">
                                <?= /* @noEscape */ $block->currency(floor($vetSession['grand_total'])) ?>
                            </p>
                        </div>
                        <?php if (!empty($vetSession['wallet_discount_amount']) && empty($vetSession['coupon_discount_amount'])) : ?>
                            <div class="coupon-saved">
                                <p class="saved-text"><?= __('You saved') ?></p>
                                <p class="coupon-applied"><?= /* @noEscape */ $block->currency(floor($vetSession['wallet_discount_amount'])) ?></p>
                            </div>
                            <div class="coupon-saved">
                                <p class="saved-text"><?= __('Wallet used') ?></p>
                                <p class="coupon-applied"><?= /* @noEscape */ $block->currency(floor($vetSession['wallet_discount_amount'])) ?></p>
                            </div>
                        <?php endif; ?>
                        <?php if (!empty($vetSession['coupon_discount_amount']) && empty($vetSession['wallet_discount_amount'])) : ?>
                            <div class="coupon-saved">
                                <p class="saved-text"><?= __('You saved') ?></p>
                                <p class="coupon-applied"><?= /* @noEscape */ $block->currency(floor($vetSession['coupon_discount_amount'])) ?></p>
                            </div>
                            <div class="coupon-saved">
                                <p class="saved-text"><?= __('Coupon used') ?></p>
                                <p class="saved-text"><?= /* @noEscape */ $block->currency(floor($vetSession['coupon_discount_amount'])) ?></p>
                            </div>
                        <?php endif; ?>
                        <?php if (!empty($vetSession['wallet_discount_amount']) && !empty($vetSession['coupon_discount_amount'])) :
                            $wallet = $vetSession['coupon_discount_amount'] + $vetSession['wallet_discount_amount']; ?>
                            <div class="coupon-saved">
                                <p class="saved-text"><?= __('You saved') ?></p>
                                <p class="coupon-applied"><?= /* @noEscape */ $block->currency(floor($wallet)) ?></p>
                            </div>
                            <div class="coupon-saved">
                                <p class="saved-text"><?= __('Wallet used') ?></p>
                                <p class="coupon-applied"><?= /* @noEscape */ $block->currency(floor($vetSession['wallet_discount_amount'])) ?></p>
                            </div>
                            <div class="coupon-saved">
                                <p class="saved-text"><?= __('Coupon used') ?></p>
                                <p class="saved-text"><?= /* @noEscape */ $block->currency(floor($vetSession['coupon_discount_amount'])) ?></p>
                            </div>
                        <?php endif; ?>
                        <div class="wallet selection">
                            <?php if ($block->getWalletBalance() > 0) : ?>
                                <?php if ($vetSession['coupon'] > 0) : ?>
                                    <?php if (empty($vetSession['wallet_amount'])) : ?>
                                        <fieldset class="select">
                                            <input type="checkbox" class="input" id="wallet-select" name="wallet" value="<?= $vetSession['grand_total'] ?>" />
                                            <label for="wallet-select"><?= __('Wallet Balance ('. /* @noEscape */ $block->currency(floor($block->getWalletBalance())).')') ?></label>
                                        </fieldset>
                                    <?php else : ?>
                                        <fieldset class="select">
                                            <input type="checkbox" checked class="input" id="wallet-select" name="wallet" value="<?= $vetSession['grand_total'] ?>" />
                                            <label for="wallet-select"><?= __('Wallet Balance ('. /* @noEscape */ $block->currency(floor($block->getWalletBalance())).')') ?></label>
                                        </fieldset>
                                    <?php endif;?>
                                <?php endif;?>
                            <?php endif;?>
                        </div>
                        <?php if ($vetSession['wallet'] > 0) : ?>
                            <div class="coupon-box">
                                <?php if (empty($vetSession['coupon_code'])) : ?>
                                    <input type="text" class="coupon-input" name="service-coupon" placeholder="Enter Coupon Code" />
                                    <button type="button" class="btn-coupon" id="apply-coupon"><?= __('Apply') ?></button>
                                <?php else : ?>
                                    <input type="text" class="coupon-input" name="service-coupon" placeholder="Enter Coupon Code" value="<?= $block->escapeHtml($vetSession['coupon_code']) ?>" />
                                    <button type="button" class="btn-coupon-close" id="remove-coupon">X</button>
                                <?php endif;?>
                            </div>
                        <?php endif;?>
                        <?php $showOfferHtml = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('15')->toHtml(); ?>
                        <?php if ($showOfferHtml != '') : ?>
                            <div class="gift-coupon">
                                <!-- <a href="javascript:;" class="have-gift-card"><?= __('Have a Gift Card') ?></a> -->
                                <a href="javascript:;" class="show-offers"><?= __('Show offers') ?></a>
                            </div>
                            <div class="show-offer-list content" id="offers-modal" style="display:none;">
                                <?= $showOfferHtml ?>
                            </div>
                        <?php endif; ?>
                        <?php if ($vetSession['grand_total'] > 0 ) :?>
                            <div class="offer selection">
                                <fieldset class="select">
                                    <input type="radio" class="input" id="offer-select" name="paymode" value="pay-now" />
                                    <label for="offer-select"><?= $block->escapeHtml(__('Pay Now')) ?></label>
                                </fieldset>
                            </div>
                        <?php endif; ?>
                        <button type="button" class="btn-payment-make"><?= $block->escapeHtml(__('MAKE PAYMENT')) ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $block->updateVetSession($vetSession); ?>
<div class="professional-profile-modal" style="display:none;"></div>