<?php
use Magento\Framework\View\Element\Template;
/** @var Template $block */
?>
<?php
$professionalBlock = $block->getLayout()->createBlock('Zigly\VetConsulting\Block\Vet\VetListing');
$reviewBlock = $block->getLayout()->createBlock('Zigly\Sales\Block\Order\Booking');
?>
<?php $vetDetails = $block->getData('vetData'); ?>
<div class="vet-item professional">
    <div class="vet-profile-info">
        <div class="profile-image">
            <?php $image = $professionalBlock->getProfessionalimage($vetDetails->getProfileImage());?>
            <img src="<?= $image ?>" alt="Professional Profile" >
        </div>
        <div class="profile-details">
            <p class="name"><?= $vetDetails->getName() ?></p>
            <p class="field"><?= $vetDetails->getSelectSpecialisation() ?></p>
            <p class="company"><?= $vetDetails->getName() ?></p>


            <div class="exp-reviews">
                <div class="exp">
                    <?php $experience = $vetDetails->getYearOfExperience();
                    $experience = ($experience == 0 || $experience == NULL)? '0 years of experience': "$experience years of experience"; ?>
                    <p><?= $block->escapeHtml(__($experience)) ?></p>
                    <p><?= $block->escapeHtml(__($vetDetails->getCertification())) ?></p>
                </div>
                <div class="ratings">
                    <?php if (!empty($vetDetails->getOverallRating())) { ?>
                        <p class="rating"><?= $vetDetails->getOverallRating() ?></p>
                    <?php } ?>
                    <?php if ($professionalBlock->getProfessionalReviewCount($vetDetails->getGroomerId())) { ?>
                        <p class="reviews">(<span><?= $professionalBlock->getProfessionalReviewCount($vetDetails->getGroomerId()) ?></span> reviews)</p>
                    <?php } ?>
                </div>
            </div>
        </div>
    </div>
    <div class="tab-container">
        <div class="tab-menu">
            <ul>
                <li><a href="javascript:;" class="tab-a active-a about" data-id="about">About</a></li>
                <li><a href="javascript:;" class="tab-a review" data-id="reviews">Reviews</a></li>
            </ul>
        </div>
        <!--end of tab-menu-->
        <div class="tab tab-active" data-id="about">
        <p><?= $vetDetails->getDescription() ?></p>
        </div>
        <!--end of tab one--> 
        <div class="tab" data-id="reviews">
            <div class="consult-reviews-rating">
            <?php $groomerReview = $reviewBlock->getProfessionalReviewById($vetDetails->getGroomerId());
            if (count($groomerReview)) {
                foreach ($groomerReview as $key => $value) { ?>
                    <p class="customer-name"><?= $value['customer_name'] ?></p>
                    <div class="review-block">
                        <div class="rating-review">
                            <div class="nested product-review-table" id="product-review-table">
                               <div class="choice review-field-rating">
                                  <div class="rating-stars-block">
                                    <input type="radio" <?php if ($value['star_rating'] == 5) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                    <label class="rating-star rating-5" for="Feedback_5" title="<?= $value['star_rating'] ?> stars" id="Feedback_5_label">
                                    </label>
                                    <input type="radio" <?php if ($value['star_rating'] == 4) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                    <label class="rating-star rating-4" for="Feedback_4" title="<?= $value['star_rating'] ?> stars" id="Feedback_4_label">
                                    </label>
                                    <input type="radio" <?php if ($value['star_rating'] == 3) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                    <label class="rating-star rating-3" for="Feedback_3" title="<?= $value['star_rating'] ?> stars" id="Feedback_3_label">
                                    </label>
                                    <input type="radio" <?php if ($value['star_rating'] == 2) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                    <label class="rating-star rating-2" for="Feedback_2" title="<?= $value['star_rating'] ?> stars" id="Feedback_2_label">
                                    </label>
                                    <input type="radio" <?php if ($value['star_rating'] == 1) { echo 'checked';}?> id="<?= $value['star_rating'] ?>" value="<?= $value['star_rating'] ?>" class="radio">
                                    <label class="rating-star rating-1" for="Feedback_1" title="<?= $value['star_rating'] ?> star" id="Feedback_1_label">
                                    </label>
                                  </div>
                               </div>
                            </div>
                            <p class="review-create_at"><?= 'Reviewed '.$reviewBlock->reviewedAtFormat($value['created_at']) ?></p>
                        </div>
                        <div><?= $value['description'] ?></div>
                    </div>
                <?php }
            } else { ?>
                <p>No review's found.</p>
            <?php } ?>
        </div>
        <!--end of tab two--> 
    </div>
</div>