<?php
$vetCollection = $this->getVets();
$vetSession = $block->getVetSession();
?>
<div class="vet-contanier select-vet">
    <div class="vet-layer-nav-contanier">
        <form>
            <!-- <div class="toggle-content filter-contanier">
                <button class="btn btn-filter" type="button">filter by Specialty</button>
                <div class="filter-list">
                    <ul class="list">
                        <?php// $specialty = $this->getSpecialisation();
                        //$reqSpecialty = $this->getReqSpecialty();
                        //foreach ($specialty as $val) {
                          //  $checked = '';
                            //if(is_array($reqSpecialty) && in_array($val, $reqSpecialty)){
                              //  $checked = 'checked';
                            //} ?>
                            <li class="options">
                                <input type="checkbox" <?php// $checked ?> id="<?php// $val?>" name="specialty[]" class="check-specialty" value="<?phph//$val?>">
                                <label for="<?php//$val?>"><?php//$val?></label>
                            </li>
                        <?php// } ?>
                    </ul>
                </div>
            </div> -->
            <div class="toggle-content sort-contanier">
                <button class="btn btn-sort" type="button">Sort By</button>
                <!-- sorting options -->
                <div class="filter-list">
                    <ul class="list">
                        <li class="options">
                            <input type="radio" id="rating" class="check-sort" <?php if ($this->getReqSort() == "overall_rating") { echo 'checked';}?> name="sort" value="overall_rating">
                            <label for="rating">rating</label>
                        </li>
                        <li class="options">                            
                            <input type="radio" id="fees" class="check-sort" <?php if ($this->getReqSort() == "for_vet_consulting") { echo 'checked';}?> name="sort" value="for_vet_consulting">
                            <label for="fees">fees</label>
                        </li>
                        <li class="options">
                            <input type="radio" id="experience" class="check-sort" <?php if ($this->getReqSort() == "year_of_experience") { echo 'checked';}?> name="sort" value="year_of_experience">
                            <label for="experience">experience</label>
                        </li>
                        <!-- <li class="options">
                            <input type="radio" id="distance" class="check-sort" <?php// if ($this->getReqSort() == "year_of_experience") { echo 'checked';}?> name="sort" value="year_of_experience">
                            <label for="distance">distance</label>
                        </li> -->
                    </ul>
                </div>
            </div>
        </form>
    </div>
    <?php if (!count($vetCollection)): ?>
        <div class="nodata-block">
            <div class="heading-label"><?= __('Sorry! No Vet Appointment available for your preferred Date & Time.') ?></div>

            <div class="nodata-content">
                <a href="#" class="other-service">
                    <div class="service-images">
                        <img  src="<?php echo $this->getViewFileUrl('Zigly_VetConsulting::images/vet_insta_consult.png'); ?>" />
                    </div>
                    <span class="content">
                    	<span class="content-heading">Insta consult</span>
                    	<span class="description">Book instant video call consulting with experience vet</span>
                    </span>
                </a>

                <a href="#" class="other-service">
                    <div class="service-images">
                        <img  src="<?php echo $this->getViewFileUrl('Zigly_VetConsulting::images/vet_video_consult.png'); ?>" />
                    </div>
                    <span class="content">
                    	<span class="content-heading">Book Video Appointment</span>
                    	<span class="description">Book instant video call consulting with experience vet</span>
                    </span>
                </a>
            </div>
                
        </div>
    <?php else : ?>
        <input type="hidden" name="vet_id" <?= !empty($vetSession['vet_id']) ? 'value="'.$vetSession['vet_id'].'"' : ''?>>
        <div class="vet-grid-contanier">
            <div class="vet-grid">
                <?php foreach($vetCollection as $vet) : ?>
                    <div class="vet-item professional">
                        <div class="vet-profile-info">
                            <div class="profile-image">
                                <?php $image = $block->getProfessionalimage($vet->getProfileImage());?>
                                <img src="<?= $image ?>" alt="Professional Profile" >
                                <span><?= __('ZIGLY VERIFIED') ?></span>
                            </div>
                            <div class="profile-details">
                                <p class="name"><?= $vet->getName() ?></p>
                                <?php if(!empty($vet->getSelectSpecialisation())){ ?>
                                    <p class="field"><?= $vet->getSelectSpecialisation() ?></p>
                                <?php } else { ?>
                                    <p class="field"><?= $vet->getSpecialisationOther() ?></p>
                                <?php } ?>
                                <?php if (!empty($vet->getClinicName())) { ?>
                                    <p class="company"><?= $vet->getClinicName() ?></p>
                                <?php } else { ?>
                                    <p class="company"><?= $vet->getCompanyName() ?></p>
                                <?php } ?>
                                <a href="javascript:void(0);" class="view-vet-profile" key="<?= $vet->getGroomerId() ?>"><?= __('VIEW PROFILE') ?></a>
                            </div>
                        </div>
                        <div class="additional-details">
                            <div class="place-price">
                                <div class="place">
                                    <p>3.5Km away</p>
                                    <p><?= $block->getProfessionalCityHub($vet->getCityHub()) ?></p>
                                </div>
                                <div class="price">
                                    <span class="fees"><?= /* @noEscape */ $this->currency(floor($vet->getForVetConsulting())) ?></span>
                                </div>
                            </div>
                            <div class="exp-reviews">
                                <div class="exp">
                                    <?php $experience = $vet->getYearOfExperience();
                                    $experience = ($experience == 0 || $experience == NULL)? '0 years of experience': "". floatval($experience)." years of experience"; ?>
                                    <p><?= $block->escapeHtml(__($experience)) ?></p>
                                    <p><?= $block->escapeHtml(__($vet->getCertification())) ?></p>
                                </div>
                                <div class="ratings">
                                    <?php if (!empty($vet->getOverallRating())) { ?>
                                        <p class="rating"><?= $vet->getOverallRating() ?></p>
                                    <?php } ?>
                                    <?php if ($block->getProfessionalReviewCount($vet->getGroomerId())) { ?>
                                        <p class="reviews">(<span><?= $block->getProfessionalReviewCount($vet->getGroomerId()) ?></span> reviews)</p>
                                    <?php } ?>
                                </div>
                            </div>
                            <div class="action book-appointment">
                                <button class="btn btn-book-appointment" type="button" data-schedule_id="<?= $vet->getSchedulemanagementId() ?>" data-vet_id="<?= $vet->getGroomerId() ?>">Book Appointment</button>
                            </div>
                        </div>
                    </div>
                <?php endforeach;?>
            </div>
        </div>
        <div class="professional-profile-modal" style="display:none;"></div>
    <?php endif; ?>
</div>