<?php $transactions = $this->getPastTransactions(); ?>
<?php $amounts = $this->getWalletMoney(); ?>
<?php $totalBalance = $this->getTotalBalance(); ?>
<?php $min = $this->currency(floor($this->getMinRecharge()), true, false);?>
<?php $max = $this->currency(floor($this->getMaxRecharge()), true, false);?>
<?php $helper = $this->helper('Zigly\Wallet\Helper\Data'); ?>
<div class="wallet-money-balance">
    <div class="money-list">
        <div class="wallet-total-balance">
            <div class="wallet-header">
                <h2 class="wallet-header-label">Zigly Wallet</h2>
            </div>
            <div class="wallet-total">
                <label><?= $block->escapeHtml(__('Total Balance')) ?></label>
                <label><?= $this->currency(floor($totalBalance)) ?></label>
            </div>
        </div>
        <div class="past-transactions-details">
            <div class="past-transactions-header">
                <h3 class="past-transactions-header-label">Past Transactions</h3>
            </div>
            <?php if (count($transactions)): ?>
                <div class="transactions">
                    <ul class="past-transactions-list">
                        <?php foreach ($transactions as $transaction) : ?>
                            <li class="transactions-list">
                                <div class="comment">
                                    <span><?= $block->escapeHtml($transaction->getComment()) ?></span>
                                </div>
                                <div class="total">
                                    <?php if ($transaction->getFlag() == 0): ?>
                                        <span class="wallet-minus"><?= $block->escapeHtml(__('-')) ?><?= $this->currency(floor($transaction->getAmount())) ?></span>
                                    <?php elseif ($transaction->getFlag() == 1) : ?>
                                        <span class="wallet-plus"><?= $block->escapeHtml(__('+')) ?><?= $this->currency(floor($transaction->getAmount())) ?></span>
                                    <?php endif; ?>
                                </div>
                                <div class="date">
                                    <?php $date = new \DateTime($transaction->getCreatedAt());
                                    $date->setTimezone(new \DateTimeZone('Asia/Kolkata'));
                                    $createdAt = $date->format('d M \'y h:i A'); ?>
                                    <span><?= $block->escapeHtml($createdAt) ?></span>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <?php if ($this->getPagerHtml()) : ?>
                    <div class="order-products-toolbar toolbar bottom"><?= $this->getPagerHtml() ?></div>
                <?php endif ?>
            <?php else: ?>
                <div class="message message-notice notice">No Past Transactions</div>
            <?php endif; ?>
        </div>
    </div>
    <?php if ($helper->isWalletRechargeEnabled()){ ?>
        <div class="wallet-add-amount">
            <form data-mage-init='{"validation": {}}' class="form add-money-form" id="add-amount-form" method="post">
                <div class="wallet-amount">
                    <div class="amount-header">
                        <h2 class="amount-header-label">Add Money</h2>
                    </div>
                    <div class="choose-amount">
                        <label><?= $block->escapeHtml(__('Choose an amount')) ?></label>
                        <div class="amount-control type">
                            <?php if (!empty($amounts)): ?>
                                <?php foreach($amounts as $amount){ ?>
                                    <input type="radio" name="add_amount" class="primary" id="<?php /* @noEscape */ echo $amount ?>" value="<?php /* @noEscape */ echo $amount ?>" title="<?php /* @noEscape */ echo $amount ?>" >
                                    <label class="amount-label" for="<?php /* @noEscape */ echo $amount ?>">
                                        <?php echo $amount; ?>
                                    </label>
                                <?php }?>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="add-amount-details">
                    <div class="add-amount">
                        <div class="field">
                            <div class="control">
                                <input type="text" name="amount" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');" id="amount" title="<?php echo __('Enter Amount') ?>" class="input-text" placeholder="<?php echo __('Enter Amount') ?>">
                            </div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="button" class="action primary btn-payment-amount" title="<?php  echo __('Proceed To Add Money') ?>"><span><?php echo __('Proceed To Add Money') ?></span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

            <div class="wallet-cat">
                <img src="<?php echo $this->getViewFileUrl('Zigly_Wallet::images/wallet-cat.png'); ?>">
            </div>

        </div>
    <?php } ?>
</div>

<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_Wallet/js/wallet":{
                "maxTotal" : <?php echo $this->getMaxRecharge();?>,
                "minTotal" : <?php echo $this->getMinRecharge();?>,
                "max" : "<?php echo $max;?>",
                "min" : "<?php echo $min;?>"
            }
        }
    }
</script>