<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_ShopbyLite
 */
?>
<?php
/** @var \Amasty\ShopbyLite\Block\Navigation\Component\FilterCollapsing $block */
?>
<script type="text/x-magento-init">
            {
                ".sidebar #narrow-by-list": {
                    "accordion": {
                        "multipleCollapsible": true,
                        "active": [<?= $block->escapeHtml(implode(",", $block->getFiltersExpanded()))?>]
                    }
                }
            }
</script>
