<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_ShopbyLite
 */
?>
<?php
/** @var \Amasty\ShopbyLite\Block\Navigation\Component\JsInit $block */
?>
<div data-am-js="js-init">
<script type="text/x-magento-init">
    {
        "[data-am-js='filter-item-default']": {
            "amShopbyFilterItemDefault": {}
        }
    }
</script>
</div>
