<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('experience_takecare_pets')->toHtml();?>
<div class="grooming-image pet">
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('experience_takecare_petslider')->toHtml();?>
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('experience_takecare_pets_buttons')->toHtml();?>
        
	
</div>


<script type="text/x-magento-init">
    {
      "*": {
            "Zigly_Catalog/js/product-slider":{}
        }
    }
</script>