<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Zigly\GroomingService\Block\Adminhtml\Reschedule $block
 */
$startHr = $block->getStartHr();
$startMin = $block->getStartMin();
$endHr = $block->getEndHr();
$endMin = $block->getEndMin();
$startTime = $startHr.':'.$startMin;
?>
<?php if (empty($startHr) || empty($startMin) || empty($endHr) || empty($endMin)) : ?>
    <div class="nodata-msg message-notice notice message">
        <?= __('Something went wrong. Please contact us.') ?>
    </div>
<?php else : ?>
    <?php
        $startTime = $startHr.':'.$startMin;
        if ($endHr <= 12) {
            $endTime = $endHr.':'.$endMin.' am';
        } else {
            $endTime = ((int)$endHr - 12).':'.$endMin.' pm';
        }
    ?>
    <div class="calender-date-day-selection">
        <div class="grooming-calendar">
            <div class="selection-note"><?= __('Note: Date will be selectable for next 7 days') ?></div>
            <div id="grooming-calendar-slot">
            </div>
        </div>
        <div id="grooming-timeslot">
            <div class="title"><?= __('Select Time') ?></div>
            <ol name='slots'>
                <?php
                $time = $startTime;
                while ($time) {
                    $prev = date('g:i a', strtotime($time));
                    $next = strtotime('+30mins', strtotime($time));
                    $time = date('g:i a', $next);
                    echo "<li class=\"slot-time\" data-slot=\"$prev\">$prev</li>";
                    if ($prev == ($endTime)) {
                        break;
                    }
                }
                ?>
            </ol>
        </div>
    </div>
    <?php
    $now = new \DateTime('now', new \DateTimeZone('Asia/Kolkata'));
    ?>
    <script>
    requirejs(['jquery', 'reschedulescript'], function($){
        window.endTime = "<?= $endTime ?>";
        window.startHr = "<?= $startHr ?>";
        window.endHr = "<?= $endHr ?>";
        window.endMin = "<?= $endMin ?>";
        window.serverTime = "<?= $now->format('Y-m-d H:i:s') ?>";
    });
    </script>
<?php endif; ?>
