<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_Login
 */
?>
<?php
/** @var \Magento\Customer\Block\Form\Login $block */
?>
<script type="text/javascript">
    require(['jquery'], function($) {
        $(function(){
            var timer = setInterval(function() {
                let loginhref = $(".social-login-btn").attr('href');
                if (loginhref === "#social-login-popup") {
                    clearInterval(timer);
                    $(".social-login-btn").trigger('click')
                }
            }, 200);
        });
    });
</script>