<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Customer\Helper\Address;

/** @var \Magento\Customer\Block\Form\Register $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */

/** @var Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $block->getData('addressHelper');
/** @var \Magento\Directory\Helper\Data $directoryHelper */
$directoryHelper = $block->getData('directoryHelper');
$formData = $block->getFormData();

$requestData = $block->getRequest()->getPostValue();
$showPhone = true;
$showEmail = true;
$referralCode = '';
if (!empty($requestData['telval'])) {
    $showPhone = false;
    $phonenumber = $requestData['telval'];
}
if (!empty($requestData['emailval'])) {
    $showEmail = false;
    $emailid = $requestData['emailval'];
}
if (!empty($requestData['referralcode'])) {
    $referralCode = $requestData['referralcode'];
}
$referralHelper = $this->helper(Zigly\Referral\Helper\Data::class);


?>
<script>
    require(['jquery','mage/url'], function ($, urlBuilder) {
        $(document).ready(function(){
            var email = "<?php echo $showEmail ?>"
            var phone = "<?php echo $showPhone ?>"
            if (phone == 1 && email == 1){
                window.location.href = "<?php echo $this->getUrl().'customer/account/login'?>"
            }
        });
    });
</script>
<?php $displayAll = $block->getConfig('general/region/display_all'); ?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<form class="form create account form-create-account"
      action="<?= $escaper->escapeUrl($block->getPostActionUrl()) ?>"
      method="post"
      id="form-validate"
      enctype="multipart/form-data"
      autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey') ?>
    <fieldset class="fieldset create info">
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Personal Information')) ?></span></legend><br>
        <input type="hidden" name="success_url" value="<?= $escaper->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $escaper->escapeUrl($block->getErrorUrl()) ?>">
        <?php if ($referralHelper->isEnabled()) : ?>
        <div class="field">
            <label for="referralcode" class="label"></label>
            <div class="control">
                <input type="text"
                       name="referralcode"
                       id="referralcode"
                       value="<?= $escaper->escapeHtmlAttr($referralCode) ?>"
                       title="<?= $escaper->escapeHtmlAttr(__('Referral Code')) ?>"
                       class="input-text"
                       data-mage-init='{"mage/trim-input":{}}'
                       placeholder="<?= $escaper->escapeHtml(__('Enter Referral Code')) ?>">
            </div>
        </div>
        <?php endif; ?>
        <?= $block->getLayout()
                ->createBlock(\Magento\Customer\Block\Widget\Name::class)
                ->setObject($formData)
                ->setForceUseCustomerAttributes(true)
                ->toHtml() ?>
        <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($formData->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($formData->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($formData->getGender())->toHtml() ?>
        <?php endif ?>
        <?= $block->getChildHtml('fieldset_create_info_additional') ?>
    </fieldset>
    <fieldset class="fieldset create account"
              data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>">
        <?php if ($showEmail) : ?>
            <div class="field">
                <label for="email_address" class="label"></label>
                <div class="control">
                    <input type="email"
                           name="email"
                           autocomplete="email"
                           id="email_address"
                           value="<?= $escaper->escapeHtmlAttr($formData->getEmail()) ?>"
                           title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text"
                           data-mage-init='{"mage/trim-input":{}}'
                           data-validate="{required:true, 'validate-email':true}"
                           placeholder="Enter Your Email Address *">
                </div>
            </div>
            <div class="actions-toolbar email-verify" style="display:none">
                <div class="primary">
                    <button type="button" class="verify-email primary" title="<?= $block->escapeHtmlAttr(__('Verify')) ?>"><span><?= $block->escapeHtml(__('Verify')) ?></span></button>
                </div>
            </div>
        <?php else: ?>
            <input type="hidden" name="email" id="email_address" value="<?= $emailid ?>">
        <?php endif; ?>
        <?php if ($showPhone) : ?>
            <div class="field">
                <label for="phone_number" class="label"></label>
                <div class="control">
                    <input type="tel" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" name="phone_number" id="phone_number" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPhoneNumber()) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text minimum-length-10 maximum-length-10" data-validate="{required:true, 'validate-length':true}" placeholder="Enter Your Mobile Number *" data-msg-validate-length="Please enter a 10 digit mobile number." maxlength="10">
                </div>
            </div>
            <div class="actions-toolbar phone-verify" style="display:none">
                    <div class="primary">
                        <button type="button" class="verify-phone primary" title="<?= $block->escapeHtmlAttr(__('Verify')) ?>"><span><?= $block->escapeHtml(__('Verify')) ?></span></button>
                    </div>
                </div>
        <?php else: ?>
            <input type="hidden" name="phone_number" id="phone_number" value="<?= $phonenumber ?>">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button"
                    id="create-account-action"
                    class="action submit primary"
                    title="<?= $escaper->escapeHtmlAttr(__('Continue')) ?>">
                <span><?= $escaper->escapeHtml(__('Continue')) ?></span>
            </button>
        </div>
    </div>
</form>
<div id="verify-modal" style="display:none;">
    <div class="field otp-verify-form required">
        <label class="label" for="otp"><span><?= $block->escapeHtml(__('Enter OTP')) ?></span></label>
        <div class="control">
            <input type="tel" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');" name="verify_otp" id="verify-otp" title="<?= $block->escapeHtmlAttr(__('Enter OTP')) ?>" class="input-text minimum-length-4 maximum-length-4 " placeholder="Enter Your 4 Digit OTP *" data-validate="{required:true, 'validate-number':true, 'validate-length':true}" data-msg-validate-length="Please enter a 4 digit OTP." data-msg-validate-number="Please enter a 4 digit OTP." maxlength="4"/>
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" class="action primary" id="resend-otp" title="<?= $block->escapeHtmlAttr(__('Resend OTP')) ?>"><span><?= $block->escapeHtml(__('Resend OTP')) ?></span></button>
        </div>
    </div>
</div>
<div id="verify-modal-email" style="display:none;">
    <div class="field otp-verify-form required">
        <label class="label" for="otp"><span><?= $block->escapeHtml(__('Enter OTP')) ?></span></label>
        <div class="control">
            <input type="tel" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*)\./g, '$1');" name="verify_otp_email" id="verify-otp" title="<?= $block->escapeHtmlAttr(__('Enter OTP')) ?>" class="input-text minimum-length-4 maximum-length-4 " placeholder="Enter Your 4 Digit OTP *" data-validate="{required:true, 'validate-number':true, 'validate-length':true}" data-msg-validate-length="Please enter a 4 digit OTP." data-msg-validate-number="Please enter a 4 digit OTP." maxlength="4"/>
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="button" class="action primary" id="resend-otp-email" title="<?= $block->escapeHtmlAttr(__('Resend OTP')) ?>"><span><?= $block->escapeHtml(__('Resend OTP')) ?></span></button>
        </div>
    </div>
</div>
<?php $ignore = /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null';
$scriptString = <<<script
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = {$ignore};

    dataForm.mage('validation', {
script;
if ($_dob->isEnabled()):
    $scriptString .= <<<script
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
script;
else:
    $scriptString .= <<<script
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
script;
endif;
$scriptString .= <<<script
    }).find('input:text').attr('autocomplete', 'off');
});
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        },
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "form-validate"
            }
        }
    }
</script>
<!-- <script>
    require([
        'jquery',
        'mage/validation',
        'mage/mage'
    ], function ($, validation) {
        $(function(){
            console.log()
            // $(".create-account-action").on('click', this.processCreate.bind(this));
            this.createForm.find('input').keypress(
                function (event) {
                    var code = event.keyCode || event.which;
                    if (code === 13) {
                        self.processCreate();
                    }
                }
            );
        });
    });
</script> -->
<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_Login/js/verifycustomer": {
                "oldphonenumber" : "",
                "oldemail" : ""
            }
        }
    }
</script>