<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_Login
 */
?>
<div class="social-login block-container authentication">
    <div class="block social-login-customer-authentication col-mp mp-12" id="social-login-authentication">
        <div class="block-title">

        </div>
        <div class="block-content" aria-labelledby="block-customer-login-heading">
            <form class="form-customer-login" id="social-form-login" data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey') ?>
                 <fieldset class="fieldset login logpage" data-hasrequired="<?= __('* Required Fields') ?>">
                    <div class="social-login-title">
                        <div class="title-text">
                            <span id="block-customer-login-heading" role="heading"
                                      aria-level="2"><?= __("Hi-Ya Pet Parents!") ?></span>
                            <span id="block-customer-login-heading" role="heading"
                                      aria-level="2"><?= __('Let’s raise healthy and happy pets together.') ?></span>
                        </div>
                        <div class="dog-cat-image"></div>
                    </div>
                    <?= $block->getChildHtml('form_before_login_fields') ?>
                    
                    <?= $block->getChildHtml('form_additional_info_referral') ?>
                    <div class="field email required">
                        <div class="control">
                            <span class="username-prefix">+91</span>
                            <input name="username" id="social_login_email" type="tel" class="input-text minimum-length-10 maximum-length-10"
                                   value="<?= $block->escapeHtml($block->getUsername()) ?>"<?php if ($block->isAutocompleteDisabled()):
                                        ?> autocomplete="off"<?php endif; ?>
                                   title="<?= __('Mobile Number') ?>"
                                   data-validate="{required:true, 'validate-length':true}" placeholder="Enter Your Mobile Number" data-msg-validate-length="Please enter a 10 digit mobile number." maxlength="10">
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="action login primary" id="bnt-auth-mobile">
                        <span><?= __('Continue') ?></span>
                    </div>
                    <div class="agree-terms">
                        <span><?= __('By continuing, I agree to the ') ?></span>
                        <a class="action" href="<?= $block->getUrl('terms-of-use'); ?>"><span><?= __('Terms of Use') ?></span></a>
                        <?= __('and') ?>
                        <a class="action" href="<?= $block->getUrl('privacy-and-cookie-policy'); ?>"><span><?= __('Privacy & Cookie Policy ') ?></span></a>
                    </div>
                    <?= $block->getChildHtml('popup.authentication.social') ?>
                    <div class="actions-toolbar username" style="display:none;">
                        <span><?= __('Cannot access email?') ?></span>
                        <a class="action switch-to-number" href="#"><span><?= __('Use mobile no. to login') ?></span></a>
                    </div>
                    <button title="Close (Esc)" type="button" class="mfp-close close1">×</button>
                </fieldset>
                <fieldset class="fieldset login otppage" data-hasrequired="<?= __('* Required Fields') ?>" style="display:none;">
                    <div class="login-otp-title">
                        <div class="title-text">
                            <span id="block-customer-otp-heading" role="heading"
                                      aria-level="2"><?= __("Enter OTP") ?></span>
                        </div>
                    </div>
                    <div class="field password required">
                        <div class="control">
                            <div class="otp-control">
                                <input name="login_pass_1"  id="login_pass_1" type="password"
                                    class="input-text"
                                    <?= $block->isAutocompleteDisabled() ? ' autocomplete="off"' : '' ?>
                                    placeholder="-" maxlength="1" >
                                <input name="login_pass_2" id="login_pass_2" type="password"
                                    class="input-text"
                                    <?= $block->isAutocompleteDisabled() ? ' autocomplete="off"' : '' ?>
                                    placeholder="-" maxlength="1">
                                <input name="login_pass_3" id="login_pass_3" type="password"
                                    class="input-text"
                                    <?= $block->isAutocompleteDisabled() ? ' autocomplete="off"' : '' ?>
                                    placeholder="-" maxlength="1">
                                <input name="login_pass_4" id="login_pass_4" type="password"
                                    class="input-text"
                                    <?= $block->isAutocompleteDisabled() ? ' autocomplete="off"' : '' ?>
                                    placeholder="-" maxlength="1">
                            </div>
                            <input name="password" id="social_login_pass" type="password"
                                   class="input-text minimum-length-4 maximum-length-4"
                                <?= $block->isAutocompleteDisabled() ? ' autocomplete="off"' : '' ?>
                                   title="<?= __('Password') ?>"
                                   data-validate="{required:true, 'validate-length':true}" data-msg-validate-length="Please enter a 4 digit OTP." style="visibility: hidden; height: 0px; padding: 0px;">

                        </div>
                        <div class="acknowledgemsg">
                            <span class="message"><?= __('A verification code has been sent via SMS to ') ?></span>
                            <span class="mobile-num-pre">+91</span>
                            <span class="mobile-num"></span>
                        </div>
                    </div>
                    <?= $block->getChildHtml('form_additional_info') ?>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="button" class="action login primary" id="bnt-social-login-authentication">
                                <span><?= __('Continue') ?></span>
                            </button>
                        </div>
                    </div>
                    <div class="actions-toolbar resendotpblock">
                        <span><?= __('Did not receive OTP?') ?></span>
                        <a class="action" href="javascript:;" id="resendotp"><span><?= __('Resend the OTP') ?></span></a>
                        <span class="otp-timmer"><?= __('00:20') ?></span>
                    </div>
                    <div class="actions-toolbar switcher">
                        <span><?= __('Cannot access mobile no?') ?></span>
                        <a class="action switch-to-email" href="#"><span><?= __('Use email to login') ?></span></a>
                    </div>
                    <button title="Close (Esc)" type="button" class="mfp-close close1 close2">×</button>
                </fieldset>
            </form>
        </div>
    </div>
</div>
