<?php
/**
 * Copyright (C) 2021 Zigly
 * @package  Zigly_Catalog
 */
use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\Action\Action;
?>
<div class="cms-landing-page at-experience at-home">
    <?php //echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Zigly_Catalog::grooming/groming_home_slider.phtml")->toHtml();?>
    <?= $block->getLayout()->createBlock('Mageplaza\BannerSlider\Block\Widget')->setSliderId(5)->toHtml();?>
    <div class="home-wrapper">
        <?php /* <div class="grooming-services">
            <div class="grooming-text">
                <h1><strong>Professional Grooming Services<br>that put your pet's needs first</strong></h1>
            </div>
            <div class="grooming-image">
                <div class="breed-specific">
                    <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/at_home_dog.png'); ?>' alt="">
                    <div class="grooming-image-text">
                        <h3>BREED-SPECIFIC-HAIRCUTS</h3>
                        <p>Zigly certified and trained groomers <br>for your little companions.</p>
                    </div>
                </div>
                <div class="grooming-experts">
                    <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/at_home_doc_pat.png'); ?>' alt="">
                    <div class="grooming-image-text">
                        <h3>GROOMING EXPERTS</h3>
                        <p>Zigly certified and trained groomers <br>for your little companions.</p>
                    </div>
                </div>
                <div class="quality-products">
                    <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/at_home_groom.png'); ?>' alt="">
                    <div class="grooming-image-text">
                        <h3>QUALITY-PRODUCTS</h3>
                        <p>A wide variety of tested <br>products to ensure best care.</p>
                    </div>
                </div>
                <div class="modern-saloon">
                    <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/at_home_dog2.png'); ?>' alt="">
                    <div class="grooming-image-text">
                        <h3>CONVENIENCE</h3>
                        <p>Curate a package of specific<br> services you feel are required <br> for your pet</p>
                    </div>
                </div>
            </div>
                <div class="book-appoinment">
                    <button class="appoinment" id="book-now" type="submit">
                        <a href="<?= $block->getBaseUrl(). 'services/grooming/' ?>">BOOK NOW</a>
                    </button>
                </div>
        </div> */?>
        <!-- Professional Grooming Services -->
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_grooming_services')->toHtml();?>
        <!-- Professional Grooming Services -->
    </div>
    <div class="quality-petcare">
        <?php /*<div class="easy-steps">
            <div class="pet-care">
                <h1>Zigly At Home</h1>
                <h3>Enjoy best-in-class <br>grooming services <br> from the comfort of <br> your home</h3>
            </div>
            <div class="four-steps">
                <div class="total-steps">
                    <div class="your-services">
                        <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/icons_zigly_-06.png'); ?>' alt="">
                        <div class="your-services-text">
                            <p>1.Select your <br>services</p>
                        </div>
                    </div>
                    <div class="your-services">
                        <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/icons_zigly_-07.png'); ?>' alt="">
                        <div class="your-services-text">
                            <p>2.Select the <br>date &amp; time</p>
                        </div>
                    </div>
                    <div class="your-services">
                        <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/Group_3810.png'); ?>' alt="">
                        <div class="your-services-text">
                            <p>3. A groomer <br>is assigned</p>
                        </div>
                    </div>
                    <div class="your-services">
                        <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/at-home-icon.png'); ?>' alt="">
                        <div class="your-services-text">
                            <p>4.Enjoy the Zigly <br>at home</p>
                        </div>
                    </div>
                </div>
                    <div class="steps-appoinment">
                        <button id="book" class="appoinment" type="submit">
                            <a href="<?= $block->getBaseUrl(). 'services/grooming/' ?>">BOOK NOW</a>
                        </button>
                    </div>
            </div>
        </div> */?>
        <!-- ZIGLY AT HOME -->
        <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_pet_steps')->toHtml();?>
        <!-- ZIGLY AT HOME -->
    </div>
    <?php
        $plans = $block->getPlans();
        $plansHtml = '';
    ?>
    <div class="explore_our_packs">
        <span class="section-title">Explore our packs</span>
        <div class="explore-tabs">
            <?php foreach ($plans as $plan) : ?>
                <button class="tablink" onclick="openPage('essential-<?= $plan->getId() ?>', this, '#FEBD34','#183762')" id="defaultOpen"><?= $plan->getPlanName() ?></button>
                <?php $image = $block->getBannerImage($plan->getBannerImage());?>
                <?php
                $activities = explode(",", $plan->getActivity());
                $plansHtml .= '<div id="essential-'.$plan->getId().'" class="tabcontent">
                    <div class="tab-content e_plan">
                        <div class="image">
                            <img src="'.$image.'" alt="dog grooming at home service">
                        </div>
                        <div class="content">
                            <p class="price-note">*Prices may varies as per breed</p>
                            <div class="title-plan">
                                <div class="title">'.$plan->getPlanName().'</div>
                                <div class="price"><span class="price-rupee">';
                if ($plan->getPlanCategory() == '1') {
                    $plansHtml .= $block->currency(number_format((float)$plan->getData("small_price"), 2, ".", "")).'</span>
                            <span class="small"><img src="'.$block->getViewFileUrl('Zigly_GroomingService::images/clock_icon.png').'" alt="">'.$plan->getData("small_time").'mins';
                } else {

                    $plansHtml .= 'Min&nbsp;'.$block->currency(number_format((float)$plan->getData("small_minimum_price"), 2, ".", "")).'</span>
                            <span class="small"><img src="'.$block->getViewFileUrl('Zigly_GroomingService::images/clock_icon.png').'" alt="">--mins';
                }
                $plansHtml .= '       </span>
                                </div>
                            </div>
                            <div class="text">
                                <span class="d_color">What\'s Included</span>';
                foreach($activities as $activityId) {
                    $activity = $block->getActivity($activityId);
                    if (!empty($activity)) {
                        $plansHtml .= '<p>'.$escaper->escapeHtml($activity->getActivityName()).'</p>';
                    }
                }
                $plansHtml .= '</div>';
                if (!empty($plan->getDescription())) {
                    $plansHtml .= '<div class="plan-description">
                              <div class="plan-description-content">'.$plan->getDescription().'</div>
                              </div>';
                }
                $plansHtml .= '</div>
                    </div>
                    </div>';
                ?>
            <?php endforeach; ?>
        </div>

        <?= $plansHtml ?>
          <div class="steps-appoinment  btn-book-tab">
            <button id="book" class="appoinment" type="submit">
                <a href="<?= $block->getBaseUrl(). 'services/grooming/' ?>">BOOK NOW</a>
            </button>
        </div>
    </div>
    <?php
    $homeproductCollection = $block->getHomeProductCollection();
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $loggin = $block->getLayout()->createBlock('Magento\Customer\Block\Account\AuthorizationLink')->isLoggedIn();
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'product_page_image_widget_medium';
    $isShowCart = true;
    $isShowReviews = true;
    $templateType = ReviewRendererInterface::SHORT_VIEW;
    $productBlock = $this->getLayout()->createBlock("Zigly\Catalog\Block\Homepage\OurProductTabs");
    ?>
    <?php if ($homeproductCollection->getSize()) : ?>
    <div class="shop-grooming amasty-jet-theme page-with-filter page-products page-layout-2columns-left">
        <div class="title">Can’t Get A Groomer? Shop Grooming Products</div>
        <div class="products wrapper grid products-grid products">
            <ol class="products list items product-items slide-products owl-carousel" id="slide-home-product">
                <?php $iterator = 1; ?>
                <?php foreach ($homeproductCollection as $item): ?>
                    <?php
                        $ziglychoice = $item->getZiglyChoice();
                        $type = ($item->getType()) ? $item->getResource()->getAttribute('type')->getFrontend()->getValue($item) : '';
                        $colorelement = '';
                        if ($type) {
                            if (strtolower($type) == 'veg') {
                               $colorelement = 'typegreen';
                            } else {
                                if (strtolower($type) == 'non veg') {
                                    $colorelement = 'typered';
                                }
                            }
                        }
                    ?>
                    <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info">
                        <div class="product-photo-wrapper">
                            <?php if ($ziglychoice): ?>
                            <span class="ziglychoice"><?= $escaper->escapeHtml('ZIGLY\'S CHOICE'); ?></span>
                            <?php endif; ?>
                            <a title="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                               aria-label="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                               href="<?= $escaper->escapeUrl($productBlock->getProductUrl($item)) ?>"
                               class="product-item-photo">
                                <?= $productBlock->getImage($item, $image)->toHtml() ?>
                            </a>
                            <?php if ($colorelement): ?>
                            <div class="<?= $colorelement;?>"></div>
                            <?php endif; ?>
                        </div>
                        <div class="product details product-item-details">
                            <span class="product product-item-name -amtheme-name">
                                <a title="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                   aria-label="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                   href="<?= $escaper->escapeUrl($productBlock->getProductUrl($item)) ?>"
                                   class="product-item-link">
                                    <?= $escaper->escapeHtml($item->getName()) ?>
                                </a>
                            </span>
                            <?php if ($templateType && $isShowReviews): ?>
                                <?= /* @noEscape */ $productBlock->getReviewsSummaryHtml($item, $templateType, true) ?>
                            <?php endif; ?>
                            <?= /* @noEscape */ $productBlock->getProductPriceHtml($item, $type) ?>
                            <?php
                            if($item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){

                                $swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
                                echo $swatchBlock->setProduct($item)->toHtml();
                            }
                            ?>
                            <?= /* @noEscape */ $productBlock->getProductDetailsHtml($item) ?>
                            <?php if ($isShowCart): ?>
                                <div class="product actions product-item-actions">
                                    <div class="actions-primary">
                                        <?php if ($item->isSaleable()): ?>
                                            <?php $postParams = $productBlock->getAddToCartPostParams($item); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $escaper->escapeHtmlAttr($item->getSku()) ?>"
                                                  action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                  method="post">
                                                <input type="hidden"
                                                       name="product"
                                                       value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                <input type="hidden"
                                                       name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                       value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $productBlock->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($item->getIsSalable()): ?>
                                                <div class="stock available"><?= $productBlock->escapeHtml(__('In stock')) ?></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><?= $productBlock->escapeHtml(__('Out of stock')) ?></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?= ($iterator == count($productBlock->getMostViewedProductCollection()) + 1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
    <?php endif; ?>
    <?php /* <div class="takecare-pets">
        <div class="pets">
            <div class="title">Quality and Convenience - The Mantra of Zigly Tribe</div>
            <div class="subtitle">Your little bundle of joy will always be in good hands. Our groomers are not just certified but also care for your pets with all their heart. And, the best part is that your pet can enjoy all our services at home.</div>
        </div>
        <div class="grooming-image pet">
            <div class="home item">
                <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/Maskgroup64.png'); ?>' alt="">
                <div class="grooming-image-text">
                    <h3>Certified Groomers, At Your Service</h3>
                    <p>Our groomers are not just certified but also care for your <br>
                        pets with all their heart. And, the best part is that your pet <br>
                        can enjoy all our services at home.</p>
                </div>
            </div>
            <div class="home item">
                <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/Maskgroup66.png'); ?>' alt="">
                <div class="grooming-image-text">
                    <h3>Happy Pets, Happy Parents</h3>
                    <p>We ensure that your pet receives the best quality services,<br>
                        as they deserve nothing but the best. And after a good <br>
                        grooming session, your pet is ready for all the snuggle.</p>
                </div>
            </div>
        </div>

            <div class="know-btn">
                <button id="know_more" class="appoinment" type="submit">
                    <a href="<?= $block->getBaseUrl(). 'services/grooming/' ?>">Book now</a>
                </button>
            </div>
        <div class="corner-image-pethome">
            <img src='<?php echo $block->getViewFileUrl('Zigly_GroomingService::images/athome_petdog.png'); ?>' alt="">
        </div>
    </div> */?>
    <!-- Quality And Convenience -->
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_takecare_pets')->toHtml();?>
    <!-- Quality And Convenience -->
    <?php $blogs = $block->getBlog(); ?>
    <?php $mageplazaBlogBlock = $block->getLayout()->createBlock('Mageplaza\Blog\Block\Frontend'); ?>
    <?php if(!empty($blogs) && count($blogs)) :?>
        <div class="tips-for-pets">
            <div class="pets-health">
                <div class="tips-text">
                    <h1>Day-to-day Tips To Maintain Your Pet's Health</h1>
                </div>
                <div class="health-images">
                    <?php foreach($blogs as $blog) : ?>
                        <div class="health-image">
                        <?php if ($blog->getImage()): ?>
                            <div class="post-image">
                                <a href="<?= $blog->getUrl() ?>">
                                    <img class="img-responsive"
                                         src="<?= $mageplazaBlogBlock->resizeImage($blog->getImage(), '400x'); ?>"
                                         alt="<?= $block->escapeHtml($blog->getName()); ?>"/>
                                </a>
                            </div>
                        <?php endif; ?>
                        <div class="health-text">
                            <h3 class="mp-post-title">
                                <?= $blog->getName(); ?>
                            </h3>
                            <a class="post-link-title" title="<?= $block->escapeHtml($blog->getName()); ?>"
                                   href="<?= $blog->getUrl() ?>">
                               <?= __('READ NOW') ?>
                           </a>
                        </div>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif;?>
    <div class="section-review">
        <?php // echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Zigly_GroomingService::grooming/reviewslider.phtml")->toHtml();?>
    </div>
</div>
<script type="text/javascript">
    function openPage(pageName,elmnt,borderColor,color) {
      var i, tabcontent, tablinks;
      tabcontent = document.getElementsByClassName("tabcontent");
      for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
      }
      tablinks = document.getElementsByClassName("tablink");
      for (i = 0; i < tablinks.length; i++) {
        tablinks[i].style.borderColor = "";
        tablinks[i].style.color = "";
      }
      document.getElementById(pageName).style.display = "block";
      elmnt.style.borderColor = borderColor;
      elmnt.style.color = color;
    }

// Get the element with id="defaultOpen" and click on it
    document.getElementById("defaultOpen").click();
</script>
<script type="text/javascript">
    require([
    'jquery',
    'Zigly_Catalog/js/owl.carousel'
    ], function ($) {
        'use strict';
        jQuery.noConflict();
        jQuery("#slide-home-product").owlCarousel({
            nav : true,
            pagination : false,
            margin : 15,
            autoplay : false,
            dots : false,
            items : 4,
            responsiveClass:true,
            responsive:{
                0:{
                    items:1,
                    nav:false
                },
                500:{
                    items:2,
                    nav: false,
                },
                800:{
                    items: 3,
                    nav:false
                },
                1000:{
                    items: 4,
                    nav: false
                }
            }
      });
});
</script>
<?php if (isset($item)) { ?>
<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
            "product_sku": "<?= $escaper->escapeJs($item->getSku()) ?>",
            "addToCartButtonDisabledClass": "disabled -show-spinner"
        }
    }
}
</script>
<?php } ?>
