<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_Catalog
 */
?>
<?php
/**
 * @var $block Magento\Catalog\Block\Product\ListProduct
 * @var $ajaxViewModel Amasty\JetTheme\ViewModel\Catalog\Ajax
 * @var $layoutViewModel Amasty\JetTheme\ViewModel\CategoryPage\CategoryPageViewModel
 * @var $escaper Magento\Framework\Escaper
 */

use Magento\Framework\App\Action\Action;

$blockObj= $block->getLayout()->createBlock('Zigly\Catalog\Block\ProductList');
$favoriteCollection = $blockObj->getFavoriteProductCollection();
$exclusiveCollection = $blockObj->getExclusiveProductCollection();
$ajaxViewModel = $block->getAjaxViewModel();
$layoutViewModel = $block->getLayoutViewModel();
$_productCollection = $block->getLoadedProductCollection();
$_productNameType = $layoutViewModel->getProductDisplayNameType();
$_addToCartDisplay = $layoutViewModel->getDisplayAddToCartButton();
$_swatchDisplayType = $layoutViewModel->getSwatchDisplayType();
$_toShowProductItemInner = $_addToCartDisplay === 'hover' || ($_addToCartDisplay != 'always' && $_swatchDisplayType === 'hover');
// phpcs:ignore
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_mobileProductColumns = $layoutViewModel->getProductsPerLineMobile();
$_desktopProductColumns = $layoutViewModel->getProductsPerLineDesktop();
?>

<?php if (!$_productCollection->count()):?>
    <div class="message info empty">
        <span><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></span>
    </div>
<?php else:?>
    <div class="top-toolbar">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    }

    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= $escaper->escapeHtmlAttr($viewMode) ?> products-<?= $escaper->escapeHtmlAttr($viewMode) ?>">
        <ol class="products list items product-items -col-xl-<?= $escaper->escapeHtmlAttr($_desktopProductColumns)?> -col-sm-<?= $escaper->escapeHtmlAttr($_mobileProductColumns)?> -amtheme-buttons-<?= $escaper->escapeHtmlAttr($_addToCartDisplay) ?>  -amtheme-swatches-<?= $escaper->escapeHtmlAttr($_swatchDisplayType) ?>">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $count = 1;
            foreach ($_productCollection as $_product):?>
                <li class="item product product-item">
                    <div class="product-item-info" data-amtheme-js="product" data-container="product-<?= $escaper->escapeHtmlAttr($viewMode) ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }

                        $_productName = $escaper->escapeHtml($_helper->productAttribute($_product, $_product->getName(), 'name'));
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        $ziglychoice = $escaper->escapeHtml($_helper->productAttribute($_product, $_product->getZiglyChoice(), 'zigly_choice'));
                        $type = ($_product->getType()) ? $_product->getResource()->getAttribute('type')->getFrontend()->getValue($_product) : '';
                        $colorelement = '';
                        if ($type) {
                            if (strtolower($type) == 'veg') {
                               $colorelement = 'typegreen';
                            } else {
                                if (strtolower($type) == 'non veg') {
                                    $colorelement = 'typered';
                                }
                            }
                        }
                        ?>
                        <?php // Product Image ?>
                        <div class="product-photo-wrapper">
                            <?php if ($ziglychoice): ?>
                            <span class="ziglychoice"><?= $escaper->escapeHtml('ZIGLY\'S CHOICE'); ?></span>
                            <?php endif; ?>
                            <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                               class="product photo product-item-photo"
                               aria-label="<?= $escaper->escapeHtmlAttr($_productName) ?>"
                               tabindex="-1">
                                <?= $productImage->toHtml() ?>
                            </a>
                            <?php if ($addToBlock = $block->getChildBlock('addto')):?>
                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                            <?php endif; ?>
                            <?php if ($colorelement): ?>
                            <div class="<?php echo $colorelement;?>"></div>
                            <?php endif; ?>
                        </div>
                        <div class="product details product-item-details">
                            <?php if ($_product->getBrand()): ?>
                                <p>
                                    <strong class="productbrand">
                                        <?php echo $_product->getResource()->getAttribute('brand')->getFrontend()->getValue($_product);?>
                                    </strong>
                                </p>
                            <?php endif; ?>
                            <strong class="product name product-item-name -<?= $escaper->escapeHtmlAttr($_productNameType) ?>">
                                <a class="product-item-link"
                                   title="<?= $escaper->escapeHtmlAttr($_productName) ?>"
                                   aria-label="<?= $escaper->escapeHtmlAttr($_productName) ?>"
                                   href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                    <?= $escaper->escapeHtml($_productName) ?>
                                </a>
                            </strong>
                            <?php if ($layoutViewModel->getShowProductReviews()): ?>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType, true) ?>
                            <?php endif; ?>
                            <?php if ($layoutViewModel->getShowShortDescription() && $_product->getShortDescription()): ?>
                                <div class="product-item-description am-custom-scrollbar">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                </div>
                            <?php endif; ?>
                            <?php if ($viewMode !== 'list'): ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                            <?php endif; ?>
                            <?php if ($viewMode === 'list' || $_swatchDisplayType === 'always'): ?>
                                <?= $block->getProductDetailsHtml($_product) ?>
                            <?php endif; ?>
                        </div>
                        <?php if (($viewMode === 'grid' && $_toShowProductItemInner) || $viewMode === 'list'): ?>
                            <?php if ($viewMode !== 'list' && $_swatchDisplayType === 'hover'): ?>
                                <?php
                                    // if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){

                                    //     $swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
                                    //     echo $swatchBlock->setProduct($_product)->toHtml();
                                    // }
                                ?>
                                <?= $block->getProductDetailsHtml($_product) ?>
                            <?php endif; ?>
                            <div class="product-item-inner">
                        <?php endif; ?>
                            <?php if ($viewMode === 'list'): ?>
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                            <?php endif; ?>
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $escaper->escapeHtmlAttr($position) : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $escaper->escapeHtmlAttr($position) : '' ?>>
                                    <?php if ($_product->isSaleable()):?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                              action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                              data-amtheme-js="ajax-tocart"
                                              method="post">
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                                            <input type="hidden" name="<?= $escaper->escapeHtmlAttr(Action::PARAM_NAME_URL_ENCODED) ?>"
                                                   value="<?= $escaper->escapeHtmlAttr($postParams['data'][Action::PARAM_NAME_URL_ENCODED]) ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <?php if ($layoutViewModel->getDisplayAddToCartButton() !== 'none'): ?>
                                                <button type="submit"
                                                        title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                        class="action tocart primary -<?= $escaper->escapeHtmlAttr($layoutViewModel->getAlignAddToCart()) ?>">
                                                   <span class="amtheme-title"><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                                </button>
                                            <?php endif; ?>
                                        </form>
                                    <?php else:?>
                                        <?php if ($_product->isAvailable()):?>
                                            <div class="stock available"><?= $escaper->escapeHtmlAttr(__('In stock')) ?></div>
                                        <?php else:?>
                                            <div class="stock unavailable"><?= $escaper->escapeHtmlAttr(__('Out of stock')) ?></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php if (($viewMode === 'grid' && $_toShowProductItemInner) || $viewMode === 'list'): ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </li>
            <?php
                if ($favoriteCollection->count()){
                    if ($count == 6){
                        echo '<li class="item product product-item span-three">';
                        echo $block->getLayout()->createBlock("Magento\Catalog\Block\Product\ListProduct")->setTemplate("Zigly_Catalog::product/favorites.phtml")->toHtml();
                        echo '</li>';
                    }
                }
                if ($exclusiveCollection->count()) {
                    if ($count == 12){
                        echo '<li class="item product product-item span-three">';
                        echo $block->getLayout()->createBlock("Magento\Catalog\Block\Product\ListProduct")->setTemplate("Zigly_Catalog::product/exclusive.phtml")->toHtml();
                        echo '</li>';
                        $count = 0;
                    }
                }
                $count++;
            endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if ($ajaxViewModel && $ajaxViewModel->isEnabledAjaxAddToCart()):?>
        <script type="text/x-magento-init">
        {
            "[data-amtheme-js=ajax-tocart]": {
                "amAjaxCart": {
                    "actionUrl": "<?= /* @noEscape */ $ajaxViewModel->getAjaxAddToCartUrl()?>",
                    "classes":{
                        "addToCartButtonDisable": "disabled -show-spinner"
                    }
                }
            }
        }
        </script>
    <?php elseif (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>",
                    "addToCartButtonDisabledClass": "disabled -show-spinner"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
