<?php
$customerAddress = $block->getAddressCollection();
?>
<ul class="manage-detail">
    <?php if (sizeof($customerAddress) > 0): ?>
        <?php foreach ($customerAddress as $address): ?>
            <li class="detail-listing">
                <div class="detail-wrapper">
                    <input type="hidden" name="select_detail" id="select-detail_<?= $address['entity_id'] ?>" >
                    <label for="select-detail_<?= $address['entity_id'] ?>"></label>
                    <span class="detail-content">
                        <p class="street"><?php echo $address['street']; ?></p>
                        <p>
                            <span><?php echo $address['city']." - ".$address['postcode'];?></span>
                        </p>
                    </span>
                </div>
                <div class="pet-actions">
                    <a class="action edit" title="Edit" id="edit-address" data-id="<?= $address['entity_id'] ?>"><?= __('Edit') ?></a>
                    <a class="action delete" title="<?= $block->escapeHtml(__('Delete Address')) ?>" id="delete-address" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($address['entity_id']) ?>">
                        <?= $block->escapeHtml(__('Delete')) ?>
                    </a>
                </div>
                <div class="action-address">
                    <button class="select-address-action" value="<?= $address['entity_id'] ?>" id="select-address-<?= $address['entity_id'] ?>">Select</button>
                </div>
            </li>
        <?php endforeach; ?>
    <?php endif; ?>
    <li class="detail-listing add-address">
        <div class="add-detail">
            <a class="action edit" id="openslider" title="<?= $block->escapeHtml(__('Add New Address')) ?>" href="#">
                <?= $block->escapeHtml(__('Add New Address')) ?>
            </a>
        </div>
    </li>
</ul>
