<?php $blockObj = $block->getLayout()->createBlock('Magento\Sales\Block\Adminhtml\Order\View\Info');
$order = $blockObj->getOrder();?>
<?php $orderCancelReason = $this->getOrderCancelReason(); ?>
<?php $orderReturnReason = $this->getOrderReturnReason(); ?>
<div id="popup-mpdal-cancel" style="display: none;">
    <form class="comment-form" method="post" action=""
        id="form-validate" enctype="multipart/form-data"
        data-hasrequired="<?php /* @noEscape */ echo __('*') ?>"
        data-mage-init='{"validation":{}}'>
        <div id="result"></div>
        <div class="admin__page-section-item-content">
            <div class="admin__page-section-item order-comments-history">
                <?php if ($orderCancelReason) { ?>
                    <div class="admin__field">
                        <label class="admin__field-label" for="name"><span><?php /* @noEscape */ echo __('Reason to Cancel') ?></span></label>
                        <div class="admin__field-control">
                            <select name="comment" id="reason"
                                class="admin__control-select"
                                data-validate="{required:true}" required aria-required="true"
                                 >
                                <option value=""><?php /* @noEscape */ echo __('Please Select') ?></option>
                                <?php
                                foreach ($orderCancelReason as $option) : ?>
                                    <option value="<?php /* @noEscape */ echo $option ?>" id="reason">
                                        <?php /* @noEscape */ echo $option ?>
                                    </option>
                                <?php endforeach; ?>
                                <option value="nothing"><?php /* @noEscape */ echo __('Others')?></option>
                            </select>
                        </div>
                    </div>
                <?php } ?>
                <div class="admin__field">
                    <label class="admin__field-label" for="name"><span><?php /* @noEscape */ echo __('Additional Details')?></span></label>
                    <div class="admin__field-control">
                        <textarea cols="50" rows="5" name="comment" id="reasons" title="Comment"
                            class="input-text comment"></textarea>
                            <span class = "error">
                    </div>
                </div>
                <?php $policy = $this->getFrontendUrl().'cancellation-return-exchange-and-refund-policy'; ?>
                <p><?php /* @noEscape */ echo __("By submitting the request, you agree the <a href='".$policy."' target='_blank'>cancel policies</a>") ?></p>
                <div class="admin__field">
                    <button class="action primary order-cancel-reason" id="cancel" title="Submit" type="submit">
                        <span><?php /* @noEscape */ echo __('Submit')?></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
<div id="popup-mpdal-return" style="display: none;">
    <form class="comment_form" method="post" action=""
        id="form-validate" enctype="multipart/form-data"
        data-hasrequired="<?php /* @noEscape */ echo __('*') ?>"
        data-mage-init='{"validation":{}}'>
        <div id="result"></div>
        <div class="admin__page-section-item-content">
            <div class="admin__page-section-item order-comments-history">
                <?php if ($orderReturnReason) { ?>
                    <div class="admin__field">
                        <label class="admin__field-label" for="name"><span><?php /* @noEscape */ echo __('Reason To Return') ?></span></label>
                        <div class="admin__field-control">
                            <select name="comment" id="return"
                                class="admin__field-select"
                                data-validate="{required:true}" required aria-required="true"
                                 >
                                <option value=""><?php /* @noEscape */ echo __('Please Select') ?></option>
                                <?php
                                foreach ($orderReturnReason as $option) : ?>
                                    <option value="<?php /* @noEscape */ echo $option ?>" id="return">
                                        <?php /* @noEscape */ echo $option ?>
                                    </option>
                                <?php endforeach; ?>
                                <option value="nothing"><?php /* @noEscape */ echo __('Others')?></option>
                            </select>
                        </div>
                    </div>
                <?php } ?>
                <div class="admin__field">
                    <label class="admin__field-label" for="name"><span><?php /* @noEscape */ echo __('Additional Details')?></span></label>
                    <div class="admin__field-control">
                        <textarea cols="50" rows="5" name="comment" id="returns" title="Comment"
                            class="input-text comment"></textarea>
                            <span class = "error">
                    </div>
                </div>
                <?php $policy = $this->getFrontendUrl().'cancellation-return-exchange-and-refund-policy'; ?>
                <p><?php /* @noEscape */ echo __("By submitting the request, you agree the <a href='".$policy."' target='_blank'>return policies</a>") ?></p>
                <div class="admin__field">
                    <button class="action primary order-return-reason" id="return" title="Submit" type="submit">
                        <span><?php /* @noEscape */ echo __('Submit')?></span>
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Zigly_Sales/js/order_reason": {
                "orderId": "<?php echo $order->getId();?>",
                "AjaxUrl" : "<?php echo $this->getCancelUrl()?>",
                "returnUrl" : "<?php echo $this->getReturnUrl()?>"
            }
        }
    }
</script>