<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_ThankYouPage
 */
?>
<div class="admin__field-tooltip amtypage-tooltip">
    <a class="admin__field-tooltip-action action-help"
       title="<?= $block->escapeHtml(
           __('You need to save your config first to see a relevant preview of Thank You page.
Preview will be generated based on the most recent order in the system. If there are no orders, the page will be blank.
Preview generation may take some time.')
       ) ?>">
    </a>
</div>