<?php
$order = $block->getOrder();
$booking = $block->getBooking();
$invoiceDate;
$invoiceId;
if (!empty($order->getCompletedAt())) {
  $invoiceDateTime = new \DateTime($order->getCompletedAt());
  $invoiceDate = $invoiceDateTime->format('d M \'y');
  $invoiceId = 'GEC/'.strtoupper($invoiceDateTime->format('My')).'/'.sprintf('%06d', (int)$booking->getEntityId());
}
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Invoice</title>

    <style>
      * {
        padding: 0;
        margin: 0;
        box-sizing: border-box;
      }
      body {
        font-family: Helvetica;
        background-color: #fff;
        color: #1f1f1f;
      }
      .invoice {
        max-width: 100%;
        width: 100%;
        padding: 20px;
      }
      .invoice-header {
        display: table;
        width: 100%;
      }
      .invoice-header .invoice-logo {
        float: left;
      }
      .invoice-logo-details > h5 {
        font-size: 36px;
        color: #1f1f1f;
      }
      .invoice-logo-details > p {
        font-size: 14px;
        font-weight: 600;
      }
      .invoice-header .invoice-logo-details {
        float: right;
      }
      .invoice-content .invoice-details {
        width: 100%;
        display: table;
        margin: 45px 0;
        text-align: left;
      }
      .invoice-content .invoice-details > div {
        width: 33.3%;
        float: left;
      }
      .invoice-content .invoice-details > div.invoice-no {
        text-align: left;
      }
      .invoice-content .invoice-details > div.invoice-date {
        text-align: center;
      }
      .invoice-content .invoice-details > div.invoice-ref-no {
        text-align: right;
      }
      .invoice-content .invoice-details span.text {
        font-weight: 600;
      }
      .invoice-content .invoice-details span {
        font-size: 18px;
      }
      .invoice-customer-details {
        margin-bottom: 20px;
        width: 100%;
      }
      .invoice-customer-details .col {
        float: right;
        width: 50%;
      }
      .invoice-customer-details .col.invoice-customer {
        float: left;
        width: 50%;
      }

      .invoice-customer-details .invoice-service-provider.col * {
        font-size: 18px;
      }
      .invoice-customer-details .col .title {
        font-size: 20px !important;
        font-weight: 600;
        margin-bottom: 20px;
      }
      .invoice-customer-details .col .customer-name {
        font-size: 18px;
        margin-bottom: 10px;
      }
      .invoice-customer-details .col .invoice-addresses .heading {
        font-weight: normal;
        font-size: 18px;
        margin-bottom: 10px;
      }

      .invoice-customer-details .col .invoice-addresses .billing > strong,
      .invoice-customer-details
        .col
        .invoice-addresses
        .billing
        > .state-postal-code
        > strong {
        font-size: 18px;
        display: block;
      }
      .invoice-customer-details
        .col
        .invoice-addresses
        .billing
        > .state-postal-code
        > strong {
        margin-bottom: 20px;
      }
      .invoice-customer-details .col .invoice-addresses .billing > address {
        font-size: 18px;
        font-style: normal;
        margin-bottom: 10px;
      }
      .invoice-customer-details
        .col
        .invoice-addresses
        .billing
        > .state-postal-code
        p {
        font-size: 18px;
      }

      .invoice-customer-details .invoice-service-provider.col > p {
        font-size: 18px;
        margin-bottom: 10px;
      }

      .invoice-customer-details .invoice-service-provider.col > strong {
        font-size: 18px;
        margin-bottom: 20px;
        display: block;
      }

      .invoice-customer-details .invoice-service-provider.col > address {
        line-height: 1.8;
        margin-bottom: 10px;
        font-style: normal;
      }
      .invoice-customer-details
        .invoice-service-provider.col
        > .state-postal-code
        > p {
        margin: 15px 0;
      }
      table {
        font-family: DejaVu Sans;
        border-collapse: collapse;
        width: 100%;
        border-bottom: 1px solid #747474;
      }
      table > tbody > tr:first-child {
        background: #d5d5d5;
      }
      tr > th {
        font-weight: normal;
      }
      td,
      th {
        border: 1px solid #747474;
        text-align: left;
        padding: 15px 10px;
      }
      tr > td {
        text-align: left;
      }
      tr > th:nth-child(2),
      tr > td:nth-child(2) {
        text-align: left;
      }
      tr > th:last-child,
      tr > td:last-child {
        text-align: right;
      }
      tr > td {
        border-bottom: none;
        border-top: none;
      }
      table > tbody > tr:last-child td {
        border: 1px solid #747474 !important;
      }
      .table-bottom-total {
        border: 1px solid #747474;
        border-top: none;
        font-family: helvetica !important;
      }
      .table-bottom-total > .price-total {
        padding: 10px;
        border-bottom: 1px solid #747474;
      }
      .table-bottom-total > .price-total > span.total {
        font-size: 15px;
        font-weight: 600;
        text-transform: uppercase;
        width: 100%;
        display: block;
      }
      .table-bottom-total > .price-total > span.total > span {
        float: right;
      }
      .table-bottom-total > .amount-in-words {
        padding: 10px;
      }
      .table-bottom-total > .amount-in-words p {
        text-transform: capitalize;
        font-size: 15px;
        margin-bottom: 8px;
        font-weight: 600;
      }
      .invoice-customer-details {
        content: "";
        display: table;
        width: 100%;
        height: 60px;
      }
      .invoice-customer-details .col {
        float: left;
        width: 45%;
        min-height: 300px;
      }
      .invoice-customer-details .col.invoice-service-provider {
        float: right;
      }
      .invoice-customer-details .col.invoice-customer .invoice-addresses {
        content: "";
        display: table;
        width: 100%;
      }
      .invoice-customer-details
        .col.invoice-customer
        .invoice-addresses
        .billing {
        float: left;
        width: 45%;
        min-height: 300px;
        vertical-align: top;
      }
      .invoice-customer-details
        .col.invoice-customer
        .invoice-addresses
        .billing.invoice-billing {
        float: left;
      }
      .invoice-customer-details
        .col.invoice-customer
        .invoice-addresses
        .billing.invoice-shipping {
        float: right;
      }
      .invoice-content > .invoice-product-details {
        clear: both;
      }
      .invoice-content .invoice-details {
        text-align: left;
        clear: both;
      }

      .invoice-footer{
      	display: table;
      	width: 100%;
      	content: '';
      	margin-top: 50px;
      }
      .invoice-footer .col{
      	display: inline-block;
      }
      .invoice-footer .invoice-qr-code{
      	float: left;
      	width: 15%;
      }
      .invoice-footer .invoice-sign{
      	float: right;
      	width: 50%;
      	text-align: right;
      	margin-top: -20px;
      }
      .invoice-footer .invoice-qr-code img,
      .invoice-footer .invoice-sign img{
      	width: 100%;
      }
      .invoice-footer .invoice-sign img{
      	width: 50%;
      	margin-top: 30px;
      }

      .invoice-footer .invoice-sign strong{
      	clear: left;
      	font-size: 15px;
      }

    </style>
  </head>
  <body>
    <div class="invoice">
      <div class="invoice-header">
        <div class="invoice-logo">
          <img
            src="<?= $block->getLayout()->getBlock('logo')->getLogoSrc() ?>"
            alt="Company Logo "
          />
        </div>
        <div class="invoice-logo-details">
          <h5 class="logo-title">ORIGINAL TAX INVOICE</h5>
        </div>
      </div>
      <div class="invoice-content">
        <div class="invoice-details">
          <div class="invoice-ref-no">
            <span class="text"><strong>Reference no.</strong></span>
            <span class="number"><?= $block->escapeHtml($order->getRealOrderId()) ?></span>
          </div>
          <div class="invoice-date">
            <span class="text"><strong>Invoice Date</strong></span>
            <span class="number"><?= $invoiceDate ?></span>
          </div>
          <div class="invoice-no">
            <span class="text"><strong>Invoice No.</strong></span>
            <span class="number"><?= $invoiceId ?></span>
          </div>
        </div>
        <div class="invoice-customer-details">
          <div class="invoice-customer col">
            <h5 class="title"><strong>Billing Details</strong></h5>
            <h5 class="title"><strong>Customer Name</strong></h5>
            <p class="customer-name"><?= $block->escapeHtml($order->getCustomerName()) ?></p>
            <div class="invoice-addresses">
              <div class="invoice-billing billing">
                <h4 class="heading">Billing Address</h4>
                <strong>Address</strong>
                <address>
                  <?= /* @noEscape */ $block->escapeHtml($block->getAddressDetails($order->getBillingAddress())) ?>
                </address>
                <div class="state-postal-code">
                  <strong>State Name & Code</strong>
                  <p class="state">
                    <?= $order->getBillingAddress()->getRegion() ?> <span class="postal-code"><?= $block->getRegionData($order->getBillingAddress()->getRegionId())->getStateCode() ?></span>
                  </p>
                  <p>Email id: <span><?= $block->escapeHtml($order->getCustomerEmail()) ?></span></p>
                  <p>Contact number: <span><?= $block->escapeHtml($order->getBillingAddress()->getTelephone()) ?></span></p>
                </div>
              </div>
              <?php if ($order->getBillingAddress()) : ?>
              <div class="invoice-shipping billing">
                <h4 class="heading">Shipping Address</h4>
                <strong>Address</strong>
                <address>
                  <?= /* @noEscape */ $block->escapeHtml($block->getAddressDetails($order->getBillingAddress())) ?>
                </address>
                <div class="state-postal-code">
                  <strong>State Name & Code</strong>
                  <p class="state">
                    <?= $order->getBillingAddress()->getRegion() ?> <span class="postal-code"><?= $block->getRegionData($order->getBillingAddress()->getRegionId())->getStateCode() ?></span>
                  </p>
                </div>
              </div>
              <?php endif; ?>
            </div>
          </div>
          <div class="invoice-service-provider col">
            <h5 class="title"><strong>Cosmo Films Limited</strong></h5>
            <h5 class="title"><strong>Business GSTIN: </strong><?= $block->getCompanyGstin() ?></h5>
            <p><strong>PAN: </strong><?= $block->getCompanyPan() ?></p>
            <p><strong>CIN: </strong><?= $block->getCompanyCin() ?></p>
            <strong>Address</strong>
            <address>
              <?= $block->getCompanyAddress() ?>
            </address>
            <div class="state-postal-code">
              <strong>State Name & Code</strong>
              <p class="state"> <?= $block->getCompanyState() ?></p>
            </div>
            <div class="state-postal-code">
              <strong>Place of Supply</strong>
              <p class="state">
                <?= $order->getBillingAddress()->getRegion() ?> <span class="postal-code"><?= $block->getRegionData($order->getBillingAddress()->getRegionId())->getStateCode() ?></span>
              </p>
            </div>
          </div>
        </div>
        <div class="invoice-product-details">
          <table>
            <tr>
              <th>S.no</th>
              <th>Description</th>
              <th>Unit Price</th>
              <th>Discount</th>
              <th>Qty</th>
              <th>Net Amount</th>
              <th>Tax Rate</th>
              <th>Tax Type</th>
              <th>Tax Amount</th>
              <th>Total Amount</th>
            </tr>
            <?php
              $grandTotal = (int)$booking->getGrandTotal();
              $gstAmount = $grandTotal * 0.09;
              $subtotal = $grandTotal - ($gstAmount * 2);
            ?>
            <tr>
              <td>1</td>
              <td><strong><?= $block->escapeHtml($booking->getPlanName())." (".$booking->getProductSku().")" ?> </strong>| HSN: <?= $block->getHsnService() ?></td>
              <td><?= $block->currency($subtotal); ?></td>
              <td><?= $block->currency($booking->getCouponAmount()); ?></td>
              <td>1</td>
              <td><?= $block->currency($subtotal); ?></td>
              <td>9%</td>
              <td>CGST</td>
              <td><?= $block->currency($gstAmount); ?></td>
              <td>
                <span class="total-price"><?= $block->currency($booking->getGrandTotal()); ?></span>
              </td>
            </tr>
            <tr style="border: none;">
              <td></td>
              <td>Wallet Used (<?= $block->currency($booking->getWalletMoney()); ?>)</td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td>9%</td>
              <td>SGST</td>
              <td><?= $block->currency($gstAmount); ?></td>
              <td>
                <span class="total-price"><?= $block->currency($booking->getGrandTotal()); ?></span>
              </td>
            </tr>
          </table>
          <div class="table-bottom-total">
            <div class="amount-in-words">
              <p class="total"><strong>amount in words</strong></p>
              <p><strong><?= $block->amountInWords($booking->getGrandTotal()); ?></strong></p>
            </div>
          </div>
        </div>

        <div class="invoice-footer">
        	<div class="invoice-qr-code col">
            <?php
              $qrCodeString = "GSTIN: ".$block->getCompanyGstin()."\r\n UPI ID: ".$block->getCompanyUpi()."\r\n Bank A/C number: ".$block->getCompanyBankno()."\r\n Invoice Number: ".$invoiceId."\r\n Invoice Date: ".$invoiceDate."\r\n Total Invoice Value: ".$booking->getGrandTotal()." \r\n GST: ".(string)($gstAmount * 2);

            ?>
            <img src="<?= 'https://chart.googleapis.com/chart?chs=200x200&cht=qr&chl='.$qrCodeString.'&choe=UTF-8' ?>" alt="QR code for scan" />

        	</div>
        	<div class="invoice-sign col">
        		<img src="<?php echo $this->getViewFileUrl('Zigly_Sales::images/sign.jpg'); ?>" alt="Signature" />
        		<strong>For Cosmo Films Limited Authorised Signatory</strong>
        	</div>
        </div>
      </div>
      <span style="position: fixed; bottom: 40px; text-align: center; width: 100%; white-space: nowrap;"><strong style="font-weight: normal;"><?= $block->getCompanyFooter() ?></strong></span>
    </div>
  </body>
</html>
