<?php
/**
 * Copyright (C) 2020  Zigly
 * @package  Zigly_Catalog
 * @var $block \Zigly\Catalog\Block\Catalog\ForPuppy
 */

use Magento\Catalog\Block\Product\ReviewRendererInterface;
use Magento\Framework\App\Action\Action;

$type = 'widget-product-grid';
$mode = 'grid';
$image = 'product_page_image_widget_medium';
$isShowCart = true;
$isShowReviews = true;
$templateType = ReviewRendererInterface::SHORT_VIEW;
$childCategoryCollection = $block->getChildCollectionToDisplayProducts();
$childListingData = [];
?>

<?php if (!empty($childCategoryCollection) && count($childCategoryCollection)) : ?>
<div class="category-tags-container">
<?php foreach ($childCategoryCollection as $category) : ?>
    <?php $childProductCollection = $block->getChildProductCollection($category->getEntityId());?>
    <?php if (count($childProductCollection)) : ?>
    <?php $childListingData[$category->getEntityId()]['name'] = str_replace("DOG ", "", $category->getName()); ?>
    <?php $childListingData[$category->getEntityId()]['url'] = $block->getCategoryUrl($category->getUrl()); ?>
    <?php $childListingData[$category->getEntityId()]['products'] = $childProductCollection; ?>
    <div class="category-tag">
        <a class="category-link" href="#child-<?= $category->getEntityId() ?>"><?= str_replace("DOG ", "", $category->getName()) ?></a>
    </div>
    <?php endif; ?>
<?php endforeach; ?>
</div>
<?php if (count($childListingData)) : ?>
<?php foreach ($childListingData as $categoryId => $displayCategory) : ?>
    <div class="child-category-container" id="child-<?= $categoryId ?>">
        <h3 class="amtheme-heading">
            <?= $escaper->escapeHtml($displayCategory['name']) ?>
        </h3>
        <div class="block content"
                     id="amtheme-tabs-widget-popular"
                     data-role="content">
            <div class="products products-grid grid -display-block">
                <ol class="products product-items amtheme-products-secondary amtheme-slick-slider -full-width -slick-arrows-hover"
                            data-mage-init='{"slickSlider": {
                                "isOnMobile": "false",
                                "updateOnResize": true,
                                "responsiveSettings": {
                                    "responsive": [
                                        {
                                            "breakpoint": 991,
                                            "settings": {
                                                "slidesToShow": 3,
                                                "draggable": "true"
                                            }
                                        },
                                        {
                                            "breakpoint": 767,
                                            "settings": {
                                                "slidesToShow": 2,
                                                "arrows": "false",
                                                "draggable": "true"
                                            }
                                        },
                                        {
                                            "breakpoint": 480,
                                            "settings": {
                                                "slidesToShow": 1,
                                                "arrows": "false",
                                                "draggable": "true"
                                            }
                                        }
                                    ]
                                },
                                "sliderOptions": {
                                    "slidesToShow": 4,
                                    "slidesToScroll": 1,
                                    "infinite": false,
                                    "arrows": true,
                                    "dots": false,
                                    "autoplay": false,
                                    "autoplaySpeed": 0,
                                    "draggable": false,
                                    "lazyLoad": "ondemand"
                                }
                            }}'>
                    <?php $iterator = 1; ?>
                    <?php foreach ($displayCategory['products'] as $item): ?>
                        <?php
                        $ziglychoice = $item->getZiglyChoice();
                        $type = ($item->getType()) ? $item->getResource()->getAttribute('type')->getFrontend()->getValue($item) : '';
                        $colorelement = '';
                        if ($type) {
                            if (strtolower($type) == 'veg') {
                               $colorelement = 'typegreen';
                            } else {
                                if (strtolower($type) == 'non veg') {
                                    $colorelement = 'typered';
                                }
                            }
                        }
                        ?>
                        <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                        <div class="product-item-info">
                            <div class="product-photo-wrapper">
                                <?php if ($ziglychoice): ?>
                                <span class="ziglychoice"><?= $escaper->escapeHtml('ZIGLY\'S CHOICE'); ?></span>
                                <?php endif; ?>
                                <a title="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                   aria-label="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                   href="<?= $escaper->escapeUrl($block->getProductUrl($item)) ?>"
                                   class="product-item-photo">
                                    <?= $block->getImage($item, $image)->toHtml() ?>
                                </a>
                                <?php if ($colorelement): ?>
                                <div class="<?= $colorelement;?>"></div>
                                <?php endif; ?>
                            </div>
                            <div class="product details product-item-details">
                                <span class="product product-item-name -amtheme-name">
                                    <a title="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                       aria-label="<?= $escaper->escapeHtmlAttr($item->getName()) ?>"
                                       href="<?= $escaper->escapeUrl($block->getProductUrl($item)) ?>"
                                       class="product-item-link">
                                        <?= $escaper->escapeHtml($item->getName()) ?>
                                    </a>
                                </span>
                                <?php if ($templateType && $isShowReviews): ?>
                                    <?= /* @noEscape */ $block->getReviewsSummaryHtml($item, $templateType, true) ?>
                                <?php endif; ?>
                                <?= /* @noEscape */ $block->getProductPriceHtml($item, $type) ?>
                                <?php
                                    if($item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){

                                        $swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
                                        echo $swatchBlock->setProduct($item)->toHtml();
                                    }
                                ?>
                                <?= /* @noEscape */ $block->getProductDetailsHtml($item) ?>
                                <?php if ($isShowCart): ?>
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($item->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($item); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $escaper->escapeHtmlAttr($item->getSku()) ?>"
                                                      action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                                      method="post">
                                                    <input type="hidden"
                                                           name="product"
                                                           value="<?= $escaper->escapeHtmlAttr($postParams['data']['product']) ?>">
                                                    <input type="hidden"
                                                           name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($item->getIsSalable()): ?>
                                                    <div class="stock available"><?= $block->escapeHtml(__('In stock')) ?></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><?= $block->escapeHtml(__('Out of stock')) ?></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($childProductCollection) + 1) ? '</li>' : '' ?>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
        <div class="view-more-product">
            <a class="action primary" href="<?= $displayCategory['url'] ?>"><?= __('View All') ?></a>
        </div>
    </div>
<?php endforeach; ?>

<?php endif; ?>

<?php endif; ?>


<?php if (isset($item)) : ?>
<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {
            "product_sku": "<?= $escaper->escapeJs($item->getSku()) ?>",
            "addToCartButtonDisabledClass": "disabled -show-spinner"
        }
    }
}
</script>
<?php endif; ?>


<script type="text/javascript">

    require(['jquery'], function ($) {
    $(document).ready(function() {
        $(document).on('click', 'a[href^="#"]', function(e) {
            var id = $(this).attr('href');
            var $id = $(id);
            if ($id.length === 0) {
            return;
        }
        e.preventDefault();
        var pos = $id.offset().top;
        $('body, html').animate({scrollTop: pos});
        });
    });
});

</script>


<style type="text/css">
.catalog-puppy-index .view-more-product {
    text-align: center;
}
.catalog-puppy-index .view-more-product > a {
    margin: 20px 0;
    color: #fff;
    font-size: 16px;
    text-transform: uppercase;
    padding: 12px 26px;
    text-decoration: none;
    text-align: center;
    border-radius: 24px;
}
</style>
