<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
	<legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend><br></p>
 
	<div class="field buyergst" data-container="change-buyergst">
		<label class="label" for="buyergst"><span><?php echo __('GST Number#') ?></span></label>
		<div class="control">
			<input type="text" name="buyergst" id="buyergst" autocomplete="buyergst" data-input="change-buyergst" title="<?php echo __('GST Number#') ?>" class="input-text" data-validate="{required:true}" />
		</div>
	</div>
</fieldset>  